#!/usr/bin/env python3
"""
Reset all auto-generated and manually curated data files.
This clears everything so we can start fresh from game source.
"""

import shutil
from pathlib import Path

from common_paths import DATA_DIR, GUIDES_DATA_DIR, REPO_ROOT

# Files and directories to delete/reset
TO_RESET = {
    # Auto-generated files
    'items.external.ts': GUIDES_DATA_DIR / 'items.external.ts',
    
    # Abilities directory (all auto-generated)
    'abilities_dir': GUIDES_DATA_DIR / 'abilities',
    
    # abilities.ts depends on abilities/ directory, so it will be broken
    'abilities.ts': GUIDES_DATA_DIR / 'abilities.ts',
    
    # Base item files (will be regenerated)
    'items.raw-materials.ts': GUIDES_DATA_DIR / 'items.raw-materials.ts',
    'items.weapons.ts': GUIDES_DATA_DIR / 'items.weapons.ts',
    'items.armor.ts': GUIDES_DATA_DIR / 'items.armor.ts',
    'items.tools.ts': GUIDES_DATA_DIR / 'items.tools.ts',
    'items.potions.ts': GUIDES_DATA_DIR / 'items.potions.ts',
    'items.scrolls.ts': GUIDES_DATA_DIR / 'items.scrolls.ts',
    'items.buildings.ts': GUIDES_DATA_DIR / 'items.buildings.ts',
    'items.ts': GUIDES_DATA_DIR / 'items.ts',  # Combines all items
    
    # Manually curated but should be regenerated
    'buildings.ts': GUIDES_DATA_DIR / 'buildings.ts',
    'classes.ts': GUIDES_DATA_DIR / 'classes.ts',
    'derivedClasses.ts': GUIDES_DATA_DIR / 'derivedClasses.ts',
    
    # JSON extraction results (will be regenerated)
    'ability_descriptions.json': DATA_DIR / 'ability_descriptions.json',
    'item_stats.json': DATA_DIR / 'item_stats.json',
    'buildings.json': DATA_DIR / 'buildings.json',
    'units.json': DATA_DIR / 'units.json',
    'recipes.json': DATA_DIR / 'recipes.json',
    'abilities.json': DATA_DIR / 'abilities.json',
    
    # Old extraction files
    'new_abilities.ts': REPO_ROOT / 'external/new_abilities.ts',
}

# Files to preserve (none - everything will be regenerated)
TO_PRESERVE = []

PLACEHOLDER_NOTICE = """// Placeholder file generated by reset_all_data.py
// Run `python src/features/infrastructure/extraction/scripts/current/manage_extraction.py pipeline`
// to rebuild this data from source files.
"""

PLACEHOLDER_CLASSES = f"""{PLACEHOLDER_NOTICE}
export type TrollClassData = {{
  slug: string;
  name: string;
  summary: string;
  iconSrc?: string;
  subclasses: string[];
  superclasses?: string[];
  tips?: string[];
  growth: {{ strength: number; agility: number; intelligence: number }};
  baseAttackSpeed: number;
  baseMoveSpeed: number;
  baseHp: number;
  baseMana: number;
}};

export const BASE_TROLL_CLASSES: TrollClassData[] = [];

export function getClassBySlug(_slug: string): TrollClassData | undefined {{
  return undefined;
}}

export const BASE_TROLL_CLASS_SLUGS: string[] = [];
"""

PLACEHOLDER_DERIVED_CLASSES = f"""{PLACEHOLDER_NOTICE}
export type DerivedClassType = 'sub' | 'super';

export type DerivedClassData = {{
  slug: string;
  name: string;
  parentSlug: string;
  type: DerivedClassType;
  summary: string;
  iconSrc?: string;
  tips?: string[];
  growth: {{ strength: number; agility: number; intelligence: number }};
  baseAttackSpeed: number;
  baseMoveSpeed: number;
  baseHp: number;
  baseMana: number;
}};

export const DERIVED_CLASSES: DerivedClassData[] = [];

export const SUBCLASS_SLUGS: string[] = [];
export const SUPERCLASS_SLUGS: string[] = [];

export function getDerivedBySlug(_slug: string): DerivedClassData | undefined {{
  return undefined;
}}

export function getSubclassesByParentSlug(_parentSlug: string): DerivedClassData[] {{
  return [];
}}

export function getSupersByParentSlug(_parentSlug: string): DerivedClassData[] {{
  return [];
}}
"""

PLACEHOLDER_ABILITIES = f"""{PLACEHOLDER_NOTICE}
export type AbilityCategory =
  | 'basic'
  | 'hunter'
  | 'beastmaster'
  | 'mage'
  | 'priest'
  | 'thief'
  | 'scout'
  | 'gatherer'
  | 'subclass'
  | 'superclass'
  | 'item'
  | 'building'
  | 'unknown';

export type AbilityData = {{
  id: string;
  name: string;
  category: AbilityCategory;
  classRequirement?: string;
  description: string;
  manaCost?: number;
  cooldown?: number;
  range?: number;
  duration?: number;
  damage?: string;
  effects?: string[];
}};

export const ABILITIES: AbilityData[] = [];

export const ABILITY_CATEGORIES: Record<AbilityCategory, string> = {{
  basic: 'Basic Abilities',
  hunter: 'Hunter Abilities',
  beastmaster: 'Beastmaster Abilities',
  mage: 'Mage Abilities',
  priest: 'Priest Abilities',
  thief: 'Thief Abilities',
  scout: 'Scout Abilities',
  gatherer: 'Gatherer Abilities',
  subclass: 'Subclass Abilities',
  superclass: 'Superclass Abilities',
  item: 'Item Abilities',
  building: 'Building Abilities',
  unknown: 'Unknown Abilities',
}};

export function getAbilitiesByCategory(_category: AbilityCategory): AbilityData[] {{
  return [];
}}

export function getAbilitiesByClass(_classSlug: string): AbilityData[] {{
  return [];
}}

export function getAbilityById(_id: string): AbilityData | undefined {{
  return undefined;
}}

export function searchAbilities(_query: string): AbilityData[] {{
  return [];
}}
"""

PLACEHOLDER_ITEMS = f"""{PLACEHOLDER_NOTICE}
import type {{ ItemCategory, ItemData, ItemSubcategory, ItemsByCategory }} from '@/types/items';

const EMPTY_BY_CATEGORY: ItemsByCategory = {{
  'raw-materials': [],
  weapons: [],
  armor: [],
  tools: [],
  potions: [],
  scrolls: [],
  buildings: [],
}};

export const ITEMS_DATA: ItemData[] = [];
export const ITEMS_BY_CATEGORY: ItemsByCategory = EMPTY_BY_CATEGORY;

export function getItemById(_id: string): ItemData | undefined {{
  return undefined;
}}

export function getItemsByCategory(category: ItemCategory): ItemData[] {{
  return ITEMS_BY_CATEGORY[category] || [];
}}

export function getItemsBySubcategory(_subcategory: ItemSubcategory): ItemData[] {{
  return [];
}}

export function searchItems(_query: string): ItemData[] {{
  return [];
}}
"""

PLACEHOLDER_BUILDINGS = f"""{PLACEHOLDER_NOTICE}
export type BuildingData = {{
  id: string;
  name: string;
  description: string;
  hp?: number;
  armor?: number;
  craftableItems?: string[];
  iconPath?: string;
}};

export const BUILDINGS: BuildingData[] = [];

export function getBuildingById(_id: string): BuildingData | undefined {{
  return undefined;
}}

export function getBuildingsByCraftableItem(_itemId: string): BuildingData[] {{
  return [];
}}
"""

PLACEHOLDER_FILES = {
    GUIDES_DATA_DIR / "classes.ts": PLACEHOLDER_CLASSES,
    GUIDES_DATA_DIR / "derivedClasses.ts": PLACEHOLDER_DERIVED_CLASSES,
    GUIDES_DATA_DIR / "abilities.ts": PLACEHOLDER_ABILITIES,
    GUIDES_DATA_DIR / "items.ts": PLACEHOLDER_ITEMS,
    GUIDES_DATA_DIR / "buildings.ts": PLACEHOLDER_BUILDINGS,
}

def reset_file(file_path: Path, description: str):
    """Delete a file if it exists."""
    if file_path.exists():
        file_path.unlink()
        print(f"  [OK] Deleted {description}")
        return True
    else:
        print(f"  [-] {description} (not found, skipping)")
        return False

def reset_directory(dir_path: Path, description: str):
    """Delete a directory and all its contents if it exists."""
    if dir_path.exists():
        shutil.rmtree(dir_path)
        print(f"  [OK] Deleted {description}")
        return True
    else:
        print(f"  [-] {description} (not found, skipping)")
        return False

def main():
    import sys
    
    print("=" * 60)
    print("RESET ALL DATA - Clearing Auto-Generated Files")
    print("=" * 60)
    print()
    print("This will delete:")
    print("  - All auto-generated ability files")
    print("  - External items file")
    print("  - Buildings, classes, and derived classes")
    print("  - All JSON extraction results")
    print()
    print("This will preserve:")
    print("  - index.ts, itemIcon.ts (utility files)")
    print("  - Placeholder stubs for classes, derived classes, abilities, items, and buildings will be recreated if missing")
    print()
    
    # Check for --yes flag
    skip_prompt = '--yes' in sys.argv or '-y' in sys.argv
    
    if not skip_prompt:
        response = input("Continue? (yes/no): ")
        if response.lower() not in ['yes', 'y']:
            print("Cancelled.")
            return
    else:
        print("Auto-confirming (--yes flag provided)")
    
    print()
    print("Resetting files...")
    print()
    
    deleted_count = 0
    
    # Delete files
    for key, file_path in TO_RESET.items():
        if key.endswith('_dir'):
            if reset_directory(file_path, key):
                deleted_count += 1
        else:
            if reset_file(file_path, key):
                deleted_count += 1
    
    print()
    created_placeholders = 0
    for file_path, content in PLACEHOLDER_FILES.items():
        if not file_path.exists():
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(content.strip() + "\n", encoding="utf-8")
            created_placeholders += 1
            print(f"  [OK] Created placeholder {file_path.relative_to(REPO_ROOT)}")

    print()
    print("=" * 60)
    print(f"Reset complete! Deleted {deleted_count} files/directories")
    if created_placeholders:
        print(f"Created {created_placeholders} placeholder data file(s)")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Run extraction scripts to extract data from wurst files")
    print("  2. Run generation scripts to create TypeScript files from JSON")
    print("  3. Run integration scripts to add descriptions/stats")
    print()
    print("Or run: python src/features/infrastructure/extraction/scripts/current/recreate_all_data.py")

if __name__ == '__main__':
    main()

