import { ITTIconCategory } from './iconUtils';

export type IconMap = {
  abilities: Record<string, string>;
  items: Record<string, string>;
  buildings: Record<string, string>;
  trolls: Record<string, string>;
};

// Central, explicit mapping (display name/id -> icon filename without path, with extension)
export const ICON_MAP: IconMap = {
  abilities: {
    '\'Dysentery Track AKA "': 'BTNTracking.png',
    '|cffC2E8EB[|cffFF6347A|cffC2E8EB] - Locate |cff1FBF00Elk|r|cffC2E8EB and |cffFF0202Hostile Units|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347A|cffC2E8EB] - Locate |cffFF0202Trolls|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347E|cffC2E8EB] - Locate |cffFF0202Hostile Animals|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347Q|cffC2E8EB] - Locate |cff1FBF00Elk|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347R|cffC2E8EB] - Locate |cff1FBF00Elk|r|cffC2E8EB and |cffFF0202Hostile Units|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347R|cffC2E8EB] - Locate |cffFE890DHostile Building|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347S|cffC2E8EB] - Locate |cffE45AAFLiving Clay|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347W|cffC2E8EB] - Locate |cff1BE5B8Hawk|r': 'btnspy.png',
    '|cffC2E8EB[|r|cffFF6347B|r|cffC2E8EB] - Buildings Craft Recipe|r': 'btnbasicstruct.png',
    '|cffC2E8EB[|r|cffFF6347C|r|cffC2E8EB] - Melt Herbs|r': 'btnunstableconcoction.png',
    '|cffC2E8EB[|r|cffFF6347C|r|cffC2E8EB] - More Forge Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347C|r|cffC2E8EB] - More Witch Doctors Hut Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - Armor Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - More Armory Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - More Workshop Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - Special Herb Quick Make Page|r': 'BTNRightBook.png',
    'A Thief\\': 'BTNThiefPouch.png',
    'Acid Bomb': 'btnacidbomb.png',
    'Acquired Knowlede': 'btnnecromancermaster.png',
    'Advanced Item Radar': 'btnspy.png',
    'Advanced Scout Radar': 'btnspy.png',
    'Anabolic Potion': 'btnpotionred.png',
    'Anchor Soul': 'btnresurrection.png',
    'Angelic Elemental': 'btndivineintervention.png',
    'Anger': 'btnunholyfrenzy.png',
    'Animal Training': 'BTNAnimalTraining.png',
    'Anti-Magic Potion': 'btnpotionofclarity.png',
    'Anti-Magic Shell': 'btnantimagicshell.png',
    'Assassin Spells': 'btntome.png',
    'Aura Dummy: |cff1775CC0 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC1 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC10 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC2 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC3 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC4 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC5 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC6 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC7 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC8 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC9 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1FBF00Damage Reduction|r': 'btnhardenedskin.png',
    'Aura Dummy: |cff1FBF00Food dietary bonus.|r': 'btnmonsterlure.png',
    'Aura Dummy: |cff1FBF00Lesser Restoration|r': 'BTNRenew.png',
    'Aura Dummy: |cff1FBF00Makrura Carapace|r': 'BTNMakruraCarapace.png',
    'Aura Dummy: |cff1FBF00Makrura Cuirass|r': 'btnnagaarmorup3.png',
    'Aura Dummy: |cff1FBF00Snake Reflexes|r': 'BTNWindSerpentPassive.png',
    'Aura Dummy: |cff1FBF00Spell Damage Reduction|r': 'btnthickfur.png',
    'Aura Dummy: |cff1FBF00Thick Fur|r': 'BTNFrostBearPassive.png',
    'Aura Dummy: |cff1FBF00Thrill of the Hunt|r': 'BTNPantherPassive.png',
    'Aura Dummy: |cff1FBF00Wolf Voracity|r': 'BTNTimberWolfPassive.png',
    'Aura Dummy: Frost Cloak Caster': 'BTNCloakOfFrost.png',
    'Aura Dummy: Random Hat': 'btnselectheroon.png',
    'Aura Dummy: Snake Toxin': 'btnslowpoison.png',
    'Aura Dummy: Trophy Hide': 'BTNElkTrophyHide.png',
    'Aura Dummy: Zap 1': 'btnstasistrap.png',
    'Aura Dummy: Zap 2': 'btnstasistrap.png',
    'Bark Skin': 'btnthornshield.png',
    'Bear Trap': 'BTNBearTrap.png',
    'Bear\\': 'pasbtndrunkendodge.png',
    'Bone Tistle': 'btnthoriumranged.png',
    'Booster Spells': 'btnsorceressmaster.png',
    'Brambles': 'btnentanglingroots.png',
    'Build Armory': 'BTNArmory.png',
    'Build Camp Fire': 'btnfire.png',
    'Build Ensnare Trap': 'btncop.png',
    'Build Forge': 'btnforge.png',
    'Build Hatchery': 'btnsnowowl.png',
    'Build Mage Fire': 'btnfire.png',
    'Build Omnidefender': 'btnorctower.png',
    'Build Spirit Ward': 'btnabsorbmagic.png',
    'Build Storage Hut': 'BTNForestTrollHut1.png',
    'Build Tannery': 'btnpigfarm.png',
    'Build Teleport Beacon': 'btnenergytower.png',
    'Build Tent': 'BTNTent.png',
    'Build Troll Hut': 'btnspiritlodge.png',
    'Build Witch Doctor\\': 'btnvoodoolounge.png',
    'Build Workshop': 'BTNOrcLumberMill.png',
    'Camouflage': 'btnambush.png',
    'Cat\\': 'pasbtnevasion.png',
    'Chain Reveal': 'btnreveal.png',
    'Cloak': 'BTNDarkTrollTrapperCloak.png',
    'Coconut': 'BTNCoconut.png',
    'Collect Meat': 'btnmonsterlure.png',
    'Cook and collect Meat': 'btnmonsterlure.png',
    'Cook Meat': 'btnmonsterlure.png',
    'Create Philosophers\\': 'btnheartofsearinox.png',
    'Defensive Spells': 'btnmanual.png',
    'Dementia Inherited Spells': 'btnnecromanceradept.png',
    'Dementia Spells': 'btnnecromancermaster.png',
    'Dementia Summoning': 'pasbtngenericspellimmunity.png',
    'Depress': 'btnshadowpact.png',
    'Depression Aura': 'PASBTNShadowPact.png',
    'Devour': 'BTNLycanWolfBite.png',
    'Dire Bear Abilities': 'btnbearform.png',
    'Direwolf Abilities': 'btndirewolf.png',
    'Disease Potion': 'btnpotiongreen.png',
    'Dreamwalker Abilities': 'btnbookofthedead.png',
    'Drunk\\': 'btnlesserinvulneralbility.png',
    'Earth Guardians': 'btngolemstormbolt.png',
    'Elementalist Spells': 'btnmanual.png',
    'Endurance': 'btnheadhunterberserker.png',
    'Entangling Root Scroll': 'btnscrollofregenerationgreen.png',
    'Fervor Potion': 'btngreaterinvulneralbility.png',
    'Find Clay Balls': 'btnthunderlizardegg.png',
    'Find Flints': 'btnstaffofsanctuary.png',
    'Find Mana Crystals': 'btnmanastone.png',
    'Find Mushrooms': 'BTNMushroom.png',
    'Find Sticks': 'btnnaturetouchgrow.png',
    'Find Stones': 'btngolemstormbolt.png',
    'Find Tinders': 'btnshimmerweed.png',
    'Firebolt': 'btnfirebolt.png',
    'Flame Spray': 'btnfirebolt.png',
    'Fortitude': 'pasbtndevotion.png',
    'Friend Of The Hive': 'btnskeletonwarrior.png',
    'Full Heal': 'btnmarkoffire.png',
    'Gatherer Salves': 'btnbarrel.png',
    'Greater Hawk abilities': 'btntome.png',
    'Greater Reveal': 'btnreveal.png',
    'Grow Pet': 'BTNAdvanceLife.png',
    'Hatch': 'btnphoenixegg.png',
    'Hawk Eye': 'btnscout.png',
    'Hawk Inherited Spells': 'btntome.png',
    'Healing': 'btnhealingwave.png',
    'Healing Salve': 'BTNBronzeBowlFullGreen.png',
    'Healing wave': 'btnhealingwave.png',
    'Health Rejuv': 'btnreplenishhealth.png',
    'Hibernate': 'BTNAbility_Hibernation.png',
    'Hide Tracking Beacon': 'btnspy.png',
    'Hydra Claw Poison': 'btnimprovedstrengthofthewild.png',
    'Hypnosis': 'pasbtnelunesblessing.png',
    'Hypnotist Spells': 'btnbookofthedead.png',
    'Howl of Terror': 'BTNLoneWolf.png',
    'Item Radar': 'btnspy.png',
    'Item Warp': 'btnneutralmanashield.png',
    'Jealousy': 'btnsacrifice.png',
    'Juggernaut Inherited Spells': 'BTNTrollPredator.png',
    'Lightning Shield': 'btnlightningshield.png',
    'Mage Inherited Spells': 'btnnecromanceradept.png',
    'Magic Mist': 'btncloudoffog.png',
    'Magical Evasion Spells': 'btnspellbookbls.png',
    'Make Temporary Mage Fire': 'btnfire.png',
    'Mana Rejuv': 'btnreplenishmana.png',
    'Master Healer Spells': 'btnsorceressmaster.png',
    'Maximum Fervor': 'btnberserk.png',
    'Meditate': 'BTNMedidate.png',
    'Melt a Native Herb': 'BTNYellowHerb.png',
    'Melt a River Root': 'btnwandofneutralization.png',
    'Melt a River Stem': 'btndotadepttraining.png',
    'Melt an Exotic Herb': 'BTNPurpleHerb.png',
    'Melt everything': 'btndizzy.png',
    'Mental quickness.': 'BTNContortionist.png',
    'Metronome': 'btnwandofmanasteal.png',
    'Mix Energy': 'btnmanadrain.png',
    'Mix Health': 'btnlifedrain.png',
    'Mix Heat': 'BTNHeatDrain.png',
    'Mix Herb': 'btnunstableconcoction.png',
    'Mud Hut Resilience': 'pasbtndevotion.png',
    'Nature\\': 'btnnaturetouchgrow.png',
    'Necromancer\\': 'btnskeletonwarrior.png',
    'Negative Blast': 'btnwandofshadowsight.png',
    'Nether Fade': 'btnbanish.png',
    'Oberserver Spells': 'btntome.png',
    'Offensive Spells': 'btnnecromanceradept.png',
    'OmniCure': 'btnbigbadvoodoospell.png',
    'Omnicure Potion': 'btnminorrejuvpotion.png',
    'Omnigatherer Inherited Spells': 'btntome.png',
    'Open Light Gate': 'btnsell.png',
    'Owl Gathering Radius': 'btnsnowowl.png',
    'Owl Health': 'btnsnowowl.png',
    'Owl Movement Radius': 'btnsnowowl.png',
    'Owl Speed': 'btnsnowowl.png',
    'Pack Up': 'btnpackbeast.png',
    'Pass Meat': 'BTNPassMeat6.png',
    'Pet Sleep': 'btnelunesblessing.png',
    'Pet Spells': 'BTNBeastCall.png',
    'Physical Evasion Spells': 'btnspellbookbls.png',
    'Poison': 'BTNPoisonFang.png',
    'Priest Inherited Spells': 'btnmanual.png',
    'Prowl': 'BTNPantherProwl.png',
    'Pump Up': 'btnbloodlust.png',
    'Query Tracking Beacon': 'btnspy.png',
    'Quick make Acid Bomb': 'btnacidbomb.png',
    'Quick make Anabolic Boots': 'btnwirtsotherleg.png',
    'Quick make Anabolic Potion': 'btnpotionred.png',
    'Quick make Anti-Magic Potion': 'btnpotionofclarity.png',
    'Quick make Armory Kit': 'BTNArmory.png',
    'Quick make Battle Armor': 'btnnagaarmorup2.png',
    'Quick make Battle Axe': 'btnorcmeleeupthree.png',
    'Quick make Battle Gloves': 'btnimprovedunholystrength.png',
    'Quick make Battle Shield': 'btnarcanitearmor.png',
    'Quick make Battle Staff': 'BTNBattleStaff.png',
    'Quick make Blow Gun': 'btnalleriaflute.png',
    'Quick make Bone Boots': 'BTNBoneBoots.png',
    'Quick make Bone Coat': 'BTNBoneCoat.png',
    'Quick make Bone Gloves': 'btngauntletsofogrepower.png',
    'Quick make Bone Shield': 'btnimprovedunholyarmor.png',
    'Quick make Boots of Bear\\': 'BTNBootsOfBearTenacity.png',
    'Quick make Boots of Wolf\\': 'BTNBootsOfWolfStamina.png',
    'Quick make Camp Fire Kit': 'btnfire.png',
    'Quick make Chameleon Hatchet': 'BTNChameleonHatchetStr.png',
    'Quick make Claws of Wolf\\': 'BTNWolfSBloodlustClaws.png',
    'Quick make Cloak Of Flames': 'BTNCloakOfInferno.png',
    'Quick make Cloak Of Frost': 'BTNCloakOfFrost.png',
    'Quick make Cloak Of Healing': 'BTNCloakOfHealing.png',
    'Quick make Cloak Of Mana': 'BTNCloakOfMana.png',
    'Quick make Coat of Bear\\': 'BTNCoatOfBearPresence.png',
    'Quick make Coat of Wolf\\': 'BTNChestOfWolfVoracity.png',
    'Quick make Cure All': 'btnlesserclaritypotion.png',
    'Quick make Dark Spear': 'btnarcaniteranged.png',
    'Quick make Dark Thistles': 'btnquillspray.png',
    'Quick make Disease Potion': 'btnpotiongreen.png',
    'Quick make Drunks Potion': 'btnlesserinvulneralbility.png',
    'Quick make Elk Skin Boots': 'BTNElkHideBoots.png',
    'Quick make Elk Skin Coat': 'BTNElkHideCoat.png',
    'Quick make Elk Skin Gloves': 'BTNElkHideGloves.png',
    'Quick make EMP': 'btnwispsplode.png',
    'Quick make Ensnare Trap': 'btncop.png',
    'Quick make Fervor Potion': 'btngreaterinvulneralbility.png',
    'Quick make Fire Bomb': 'btnliquidfire.png',
    'Quick make Forge Kit': 'btnforge.png',
    'Quick make Greater Essence': 'BTNPurpleEssence.png',
    'Quick make Healing Potion': 'btnlesserrejuvpotion.png',
    'Quick make Healing Salve': 'BTNBronzeBowlFullGreen.png',
    'Quick make Hydra Scale Coat': 'btnnagaarmorup3.png',
    'Quick make Hydra Scale Gloves': 'btnimprovedstrengthofthewild.png',
    'Quick make Hunting Net': 'BTNHuntingNet.png',
    'Quick make Iron Axe': 'btnorcmeleeuptwo.png',
    'Quick make Iron Boots': 'btnboots.png',
    'Quick make Iron Coat': 'btnimprovedmoonarmor.png',
    'Quick make Iron Gloves': 'BTNIronGloves.png',
    'Quick make Iron Ingot': 'BTNIronIngot.png',
    'Quick make Iron Shield': 'btnhumanarmorupone.png',
    'Quick make Iron Spear': 'btnstrengthofthemoon.png',
    'Quick make Iron Staff': 'btnwand.png',
    'Quick make Jungle Bear Skin Boots': 'BTNBearHideBoots.png',
    'Quick make Jungle Bear Skin Coat': 'BTNBearHideCoat.png',
    'Quick make Jungle Bear Skin Gloves': 'BTNBearHideGloves.png',
    'Quick make Jungle Wolf Skin Boots': 'BTNWolfHideBoots.png',
    'Quick make Jungle Wolf Skin Coat': 'BTNWolfHideCoat.png',
    'Quick make Jungle Wolf Skin Gloves': 'BTNWolfHideGloves.png',
    'Quick make Lesser Essence': 'BTNOrangeEssence.png',
    'Quick make Living Clay': 'BTNGreenSentryWard.png',
    'Quick make Magic': 'btnmoonstone.png',
    'Quick make Magic Tree Seed': 'btnacorn.png',
    'Quick make Mana Crystal': 'BTNManaCrystal.png',
    'Quick make Mana Potion': 'btnpotionbluesmall.png',
    'Quick make Necromancer\\': 'BTNSkullShroudGlowIncreased.png',
    'Quick make Nether Potion': 'btnpotionofomniscience.png',
    'Quick make Nets': 'btnensnare.png',
    'Quick make Omnitower Kit': 'btnorctower.png',
    'Quick make Paws of Bear\\': 'BTNBearGlovesOfGreed.png',
    'Quick make Poison': 'btnhealingsalve.png',
    'Quick make Poison Spear': 'btnenvenomedspear.png',
    'Quick make Poison Thistles': 'BTNPoisonQuill.png',
    'Quick make Robe of the Magi': 'btnrobeofthemagi.png',
    'Quick make Scroll Of Cyclone': 'btnbansheemaster.png',
    'Quick make Scroll Of Entangling Root': 'btnscrollofregenerationgreen.png',
    'Quick make Scroll Of Fireball': 'btnscrollofhealing.png',
    'Quick make Scroll Of Living Dead': 'btnsnazzyscroll.png',
    'Quick make Scroll Of Stone Armor': 'btnscrolluber.png',
    'Quick make Scroll Of Swiftness': 'btnscrollofhaste.png',
    'Quick make Scroll Of Tsunami': 'btnsnazzyscrollpurple.png',
    'Quick make Shield': 'btnsteelarmor.png',
    'Quick make Smoke Bomb': 'BTNSmokepot.png',
    'Quick make Spirit Of Darkness': 'btnorbofdarkness.png',
    'Quick make Spirit Of Water': 'btnorboffrost.png',
    'Quick make Spirit Of Wind': 'btnorboflightning.png',
    'Quick make Spirit Ward': 'btnabsorbmagic.png',
    'Quick make Steel Axe': 'btnspiritwalkeradepttraining.png',
    'Quick make Steel Boots': 'BTNSteelBoots.png',
    'Quick make Steel Coat': 'btnadvancedmoonarmor.png',
    'Quick make Steel Gloves': 'btnadvancedunholystrength.png',
    'Quick make Steel Ingot': 'BTNSteelIngot.png',
    'Quick make Steel Shield': 'btnthoriumarmor.png',
    'Quick make Steel Spear': 'btnthoriumranged.png',
    'Quick make Tannery Kit': 'btnpigfarm.png',
    'Quick make Teleport Beacon Kit': 'btnenergytower.png',
    'Quick make Tent Kit': 'BTNTent.png',
    'Quick make Transport Ship': 'btnnightelftransport.png',
    'Quick make Troll Protector': 'BTNTrollProtector.png',
    'Quick make Venom Fang': 'BTNPoisonFang.png',
    'Quick make Witch Doctors Hut Kit': 'btnvoodoolounge.png',
    'Quick make Workshop Kit': 'BTNOrcLumberMill.png',
    'Radar Spells': 'btnspy.png',
    'Rage': 'btnheadhunterberserker.png',
    'Ranged heal': 'btnheal.png',
    'Recipe: Healing Salve': 'btnhealingsalve.png',
    'Recipe: Hypnosis Salve': 'pasbtnelunesblessing.png',
    'Recipe: Poison Salve': 'btnvialempty.png',
    'Recipe: Speed Salve': 'btnpotionred.png',
    'Reduce Food': 'btnmonsterlure.png',
    'Reincarnation': 'btnreincarnation.png',
    'Release Pet': 'BTNReleasePet.png',
    'Replenish Energy': 'pasbtnregenerate.png',
    'Replenish Health': 'btnholybolt.png',
    'Restore Heat': 'btnwalloffire.png',
    'Restore Mana': 'btnneutralmanashield.png',
    'Reveal': 'btnreveal.png',
    'Rip and Tear': 'pasbtnghoulfrenzy.png',
    'Rogue abilities': 'btnspellbookbls.png',
    'Sage Inherited Spells': 'btnmanual.png',
    'Sage Spells': 'btnsorceressmaster.png',
    'Scroll of Haste': 'btnscrollofhaste.png',
    'Scroll of Living Dead': 'btnskeletonwarrior.png',
    'Self Preservation': 'btnregenerate.png',
    'Sentinel': 'btnsentinel.png',
    'Shadow Sight': 'PASBTNTrollSight.png',
    'Shapeshifter Forms': 'btnbearform.png',
    'Smoke Stream': 'btncloudoffog.png',
    'Snake Reflexes': 'BTNWindSerpentPassive.png',
    'Snake Toxin': 'btnslowpoison.png',
    'Sniff': 'BTNPoisonousSmell.png',
    'Spear Cast (Stone)': 'btnthoriumranged.png',
    'Spy Inherited Spells': 'btntome.png',
    'Spirit Link': 'btnspiritlink.png',
    'Spirit Prison': 'btnwitchdoctormaster.png',
    'Stash Meat.': 'BTNFeedPet.png',
    'Steal': 'btnpickupitem.png',
    'Subclass Menu': 'btnstatup.png',
    'Summon |cff00EAFFLez|r Rune': 'BTNLezRune.png',
    'Summon |cff1FBF00Nel|r Rune': 'BTNNelRune.png',
    'Summon |cffFF0202Ka|r Rune': 'BTNKaRune.png',
    'Tame Pet': 'BTNTamePet.png',
    'Teleport Mirror': 'btnwispsplode.png',
    'Telethief Abilities': 'btnspellbookbls.png',
    'Thick Fur': 'btnthickfur.png',
    'Thieve\\': 'btnspellbookbls.png',
    'Thrill of Battle': 'BTNThrillOfBattle.png',
    'Toggle Pet Control': 'btnselectunit.png',
    'Tower Item Dummy Cast Enemy': 'btnstag.png',
    'Track': 'ATCTrack.png',
    'Tracking Trap': 'btnstasistrap.png',
    'Transform (Bear)': 'btngrizzlybear.png',
    'Transform (Panther)': 'BTNPanther.png',
    'Transform (Tiger)': 'BTNTiger.png',
    'Transform (Wolf)': 'btndirewolf.png',
    'Trap Toolkit': 'btnpackbeast.png',
    'Troll Protector Aura': 'pasbtndevotion.png',
    'Troll Targeting': 'ATCTrack.png',
    'True Sight': 'pasbtngyrocoptertruesight.png',
    'Undying': 'BTNUndying.png',
    'Vicious Strike Attack trigger': 'PASBTNViciousStrike.png',
    'Vicious Strikes True spell': 'PASBTNViciousStrike.png',
    'Way of the Hawk': 'btnnecromanceradept.png',
    'Way of the Tracker': 'btnnecromanceradept.png',
    'Ward the Area': 'BTNGreenSentryWard.png',
    'Warrior Skills': 'BTNTrollPredator.png',
    'Wolf Bite': 'BTNLycanWolfBite.png',
    'Wolf Life Steal': 'btndirewolf.png',
    'Wolf Voracity': 'BTNChestOfWolfVoracity.png',
    'Wolf\\': 'btnvampiricaura.png',
    'WOLFS_BLOODLUST_CLAWS_BLOODLUST': 'btnbloodlust.png'
  },
  items: {
    'A Thief\\': 'BTNThiefPouch.png',
    'Acid Bomb': 'btnacidbomb.png',
    'Anabolic Boots': 'btnwirtsotherleg.png',
    'Anabolic Potion': 'btnpotionred.png',
    'Anti-Magic Potion': 'btnpotionofclarity.png',
    'Armory Kit': 'BTNArmory.png',
    'Arms Slot': 'PASBTNWeaponsOfChoiceSlot.png',
    'Athelas Seed': 'BTNGreenSeed.png',
    'Banana': 'BTNBanana.png',
    'Basic Shield': 'btnsteelarmor.png',
    'Battle Armor': 'btnnagaarmorup2.png',
    'Battle Axe': 'btnorcmeleeupthree.png',
    'Battle Gloves': 'btnimprovedunholystrength.png',
    'Battle Shield': 'btnarcanitearmor.png',
    'Battle Staff': 'BTNBattleStaff.png',
    'Bear Hide': 'BTNBearHide.png',
    'Bear Skin Boots': 'BTNBearHideBoots.png',
    'Bear Skin Coat': 'BTNBearHideCoat.png',
    'Bear Skin Gloves': 'BTNBearHideGloves.png',
    'Bee Hive': 'BTNBeehive.png',
    'Blow Gun': 'btnalleriaflute.png',
    'Bone': 'BTNBone.png',
    'Bone Boots': 'BTNBoneBoots.png',
    'Bone Coat': 'BTNBoneCoat.png',
    'Bone Gloves': 'btngauntletsofogrepower.png',
    'Bone Shield': 'btnimprovedunholyarmor.png',
    'Boots of Bear\\': 'BTNBootsOfBearTenacity.png',
    'Boots of Wolfs Stamina': 'BTNBootsOfWolfStamina.png',
    'Camp Fire Kit': 'btnfire.png',
    'Chameleon Hatchet': 'BTNChameleonHatchetStr.png',
    'Clay Ball': 'btnthunderlizardegg.png',
    'Clay Explosion': 'BTNGreenSentryWard.png',
    'Claws of Wolf\\': 'BTNWolfSBloodlustClaws.png',
    'Cloak of Flames': 'BTNCloakOfInferno.png',
    'Cloak of Frost': 'BTNCloakOfFrost.png',
    'Cloak of Healing': 'BTNCloakOfHealing.png',
    'Cloak of Mana': 'BTNCloakOfMana.png',
    'Coat of bear\\': 'BTNCoatOfBearPresence.png',
    'Coat of Wolf\\': 'BTNChestOfWolfVoracity.png',
    'Coconut': 'BTNCoconut.png',
    'Cooked Meat': 'btnmonsterlure.png',
    'Cure Potion': 'btnlesserclaritypotion.png',
    'Dark Spear': 'BTNDarkSpearTrapper.png',
    'Dark Thistles': 'btnquillspray.png',
    'Disc0-Duck\\': 'btnheartofaszune.png',
    'Disease Potion': 'btnpotiongreen.png',
    'Drunk\\': 'btnlesserinvulneralbility.png',
    'Eat raw meat.': 'btncannibalize.png',
    'Elk Hide': 'BTNElkHide.png',
    'Elk Skin Boots': 'BTNElkHideBoots.png',
    'Elk Skin Coat': 'BTNElkHideCoat.png',
    'Elk Skin Gloves': 'BTNElkHideGloves.png',
    'EMP': 'btnwispsplode.png',
    'Empowered Necromancer\\': 'BTNSavageGladiatorChain.png',
    'Ensnare Trap Kit': 'btncop.png',
    'Essence Of Bees': 'BTNBeehive.png',
    'Fervor Potion': 'btngreaterinvulneralbility.png',
    'Fire Bomb': 'btnliquidfire.png',
    'Flint': 'btnstaffofsanctuary.png',
    'Food Slot.': 'BTNBearFoodSlot.png',
    'Forge Kit': 'btnforge.png',
    'Gem of Knowledge': 'btnenchantedgemstone.png',
    'Greater Essence': 'BTNPurpleEssence.png',
    'Happy Food Supplies': 'BTNBearFoodSlot.png',
    'Hatchery Kit': 'btnsnowowl.png',
    'Hawk Egg': 'btnphoenixegg.png',
    'Healing Potion': 'btnlesserrejuvpotion.png',
    'Healing Salve': 'BTNBronzeBowlFullGreen.png',
    'Hydra Claws': 'btnimprovedstrengthofthewild.png',
    'Hydra Hint': 'btnsorceressmaster.png',
    'Hydra Scale Coat': 'btnnagaarmorup3.png',
    'Hypnosis Salve': 'pasbtnelunesblessing.png',
    'Honeycomb': 'BTNHoneycomb.png',
    'Horn Of the Mammoth': 'btnhornoffog.png',
    'Hunter\\': 'BTNTrophyHideDummy.png',
    'Hunting Net': 'BTNHuntingNet.png',
    'Iron Axe': 'btnorcmeleeuptwo.png',
    'Iron Boots': 'btnboots.png',
    'Iron Coat': 'btnimprovedmoonarmor.png',
    'Iron Gloves': 'BTNIronGloves.png',
    'Iron Ingot': 'BTNIronIngot.png',
    'Iron Shield': 'btnhumanarmorupone.png',
    'Iron Spear': 'btnstrengthofthemoon.png',
    'Iron Staff': 'btnwand.png',
    'Leaf of Blue Herb': 'BTNBlueHerb.png',
    'Leaf of Exotic Herb': 'BTNPurpleHerb.png',
    'Leaf of Native Herb': 'BTNYellowHerb.png',
    'Leaf of Orange Herb': 'BTNOrangeHerb.png',
    'Lesser Essence': 'BTNOrangeEssence.png',
    'Living Clay': 'BTNGreenSentryWard.png',
    'Mage Fire Kit': 'btnfire.png',
    'Mage Masher': 'btnspiritwalkermastertraining.png',
    'Mage\\': 'btnnecromancermaster.png',
    'Magic': 'btnmoonstone.png',
    'Magic Palm Tree Seed': 'btnacorn.png',
    'Makrura Carapace': 'BTNMakruraCarapace.png',
    'Makrura Claw': 'BTNMakruraClaws.png',
    'Makruru Cuirass': 'btnnagaarmorup3.png',
    'Mana Crystal': 'BTNManaCrystal.png',
    'Mana Potion': 'btnpotionbluesmall.png',
    'Materials Slot': 'BTNResourcesPack.png',
    'Medalion of the Thief': 'btnmedalionofcourage.png',
    'Medallion of Courage': 'btnmedalionofcourage.png',
    'Mushroom': 'BTNMushroom.png',
    'Necromancer\\': 'BTNSkullShroudGlowIncreased.png',
    'Net': 'btnensnare.png',
    'Nether Potion': 'btnpotionofomniscience.png',
    'Omnicure Potion': 'btnminorrejuvpotion.png',
    'Omnitower Kit': 'btnorctower.png',
    'Panther Fang': 'BTNPantherFang.png',
    'Paws of Bear\\': 'BTNBearGlovesOfGreed.png',
    'Philosopher\\': 'btnheartofsearinox.png',
    'Poison': 'BTNPoisonFang.png',
    'Poison Spear': 'BTNPoisonSpear.png',
    'Poison Thistles': 'BTNPoisonQuill.png',
    'River Root': 'btnwandofneutralization.png',
    'River Stem': 'btndotadepttraining.png',
    'Robe of the Magi': 'btnrobeofthemagi.png',
    'Scale': 'btnnagaarmorup1.png',
    'Scavenged Mushroom': 'BTNMushroom.png',
    'Scroll of Cyclone': 'btnbansheemaster.png',
    'Scroll of Entangling Roots': 'btnscrollofregenerationgreen.png',
    'Scroll of Fire Ball': 'btnscrollofhealing.png',
    'Scroll of Haste': 'btnscrollofhaste.png',
    'Scroll of Living Dead': 'btnsnazzyscroll.png',
    'Scroll of Stone Shield': 'btnscrolluber.png',
    'Scroll of Tsunami': 'btnsnazzyscrollpurple.png',
    'Scroll Slot': 'PASBTNScrollSlot.png',
    'Smoke Bomb': 'BTNSmokepot.png',
    'Spirit Of Darkness': 'btnorbofdarkness.png',
    'Spirit Of Water': 'btnorboffrost.png',
    'Spirit Of Wind': 'btnorboflightning.png',
    'Spirit Ward Kit': 'btnabsorbmagic.png',
    'Staff of Wisdom': 'btnspiritwalkeradepttraining.png',
    'Stashed raw meat': 'BTNFeedPet.png',
    'Steel Axe': 'btnspiritwalkeradepttraining.png',
    'Steel Boots': 'BTNSteelBoots.png',
    'Steel Coat': 'btnadvancedmoonarmor.png',
    'Steel Gloves': 'btnadvancedunholystrength.png',
    'Steel Ingot': 'BTNSteelIngot.png',
    'Steel Shield': 'btnthoriumarmor.png',
    'Steel Spear': 'btnthoriumranged.png',
    'Stick': 'btnnaturetouchgrow.png',
    'Stone': 'btngolemstormbolt.png',
    'Stone Axe': 'btnorcmeleeupone.png',
    'Stone Spear': 'btnsteelranged.png',
    'Storage Hut Kit': 'BTNForestTrollHut1.png',
    'Tannery Kit': 'btnpigfarm.png',
    'Teleport beacon Kit': 'btnenergytower.png',
    'Tent Kit': 'BTNTent.png',
    'Thistles': 'btnquillsprayoff.png',
    'Tinder': 'btnshimmerweed.png',
    'Transport Ship Kit': 'btnnightelftransport.png',
    'Troll Hut Kit': 'btnspiritlodge.png',
    'Troll Protector': 'BTNTrollProtector.png',
    'Twin Island Potion': 'btnpotiongreensmall.png',
    'Ultra Poison': 'BTNUltraPoisonSpear.png',
    'Ultra Poison Spear': 'BTNUltraPoisonSpear.png',
    'Venom Fang': 'BTNPoisonFang.png',
    'Witch Doctors Hut Kit': 'btnvoodoolounge.png',
    'Wolf Hide': 'BTNWolfHide.png',
    'Wolf Skin Boots': 'BTNWolfHideBoots.png',
    'Wolf Skin Coat': 'BTNWolfHideCoat.png',
    'Wolf Skin Gloves': 'BTNWolfHideGloves.png',
    'Workshop Kit': 'BTNOrcLumberMill.png'
  },
  buildings: {},
  trolls: {},
};

export function resolveExplicitIcon(category: ITTIconCategory, key: string): string | undefined {
  // First, check the requested category
  const table = ICON_MAP[category];
  const filename = table[key];
  
  if (!filename) {
    // If not found in requested category, search all categories
    const allCategories: ITTIconCategory[] = ['abilities', 'items', 'buildings', 'trolls'];
    for (const cat of allCategories) {
      const catTable = ICON_MAP[cat];
      const foundFilename = catTable[key];
      if (foundFilename) {
        // Found the mapping, now determine which directory the file is in
        return findIconPath(foundFilename);
      }
    }
    return undefined;
  }
  
  // Found in requested category, determine which directory the file is actually in
  return findIconPath(filename);
}

/**
 * Finds the actual directory path for an icon filename.
 * Since icons can be shared across categories, we check which category
 * has this filename mapped and prefer items directory for shared icons.
 */
function findIconPath(filename: string): string {
  const allCategories: ITTIconCategory[] = ['items', 'abilities', 'buildings', 'trolls'];
  
  // Check each category to see if this filename is mapped there
  // Priority: items first (most shared icons are there), then others
  for (const cat of allCategories) {
    const catTable = ICON_MAP[cat];
    if (Object.values(catTable).includes(filename)) {
      return `/icons/itt/${cat}/${filename}`;
    }
  }
  
  // Fallback: if somehow not found, try items directory (most common)
  return `/icons/itt/items/${filename}`;
}


