import { ITTIconCategory } from './iconUtils';

export type IconMap = {
  abilities: Record<string, string>;
  items: Record<string, string>;
  buildings: Record<string, string>;
  trolls: Record<string, string>;
  units: Record<string, string>;
};

// Central, explicit mapping (display name/id -> icon filename without path, with extension)
export const ICON_MAP: IconMap = {
  abilities: {
    '\'Dysentery Track AKA "': 'BTNTracking.png',
    '[|cffffd700R|r] Ensnare': 'btnensnare.png',
    '[A] - Locate Elk and Hostile Units': 'btnspy.png',
    '[A] - Locate Trolls': 'btnspy.png',
    '[B] - Buildings Craft Recipe': 'btnbasicstruct.png',
    '[C] - More Forge Quick Make Page': 'BTNRightBook.png',
    '[C] - More Witch Doctors Hut Quick Make Page': 'BTNRightBook.png',
    '[D] - Eat Corpse': 'ATCCannibalize.png',
    '[E] - Locate Hostile Animals': 'btnspy.png',
    '[F] - Armor Quick Make Page': 'BTNRightBook.png',
    '[F] - More Armory Quick Make Page': 'BTNRightBook.png',
    '[F] - More Workshop Quick Make Page': 'BTNRightBook.png',
    '[F] - Special Herb Quick Make Page': 'BTNRightBook.png',
    '[Q] - Locate Elk': 'btnspy.png',
    '[R] - Ensnare (Ensnare Trap)': 'ATCEnsnare.png',
    '[R] - Locate Elk and Hostile Units': 'btnspy.png',
    '[R] - Locate Hostile Building': 'btnspy.png',
    '[R] - Spiked Net': 'BTNSpikedNet.png',
    '[R] - Tele-Steal Food': 'BTNTeleStealMeat.png',
    '[R] Ensnare': 'btnensnare.png',
    '[S] - Locate Living Clay': 'btnspy.png',
    '[W] - Locate Hawk': 'btnspy.png',
    '[W] - Verdant Song': 'BTNVerdantSong.png',
    '|c00ffcc00C - Grab Corpse': 'BTNCorpseGrab0.png',
    '|c00ffcc00C|r - Grab Corpse': 'BTNCorpseGrab0.png',
    '|cffC2E8EB[|cffFF6347A|cffC2E8EB] - Locate |cff1FBF00Elk|r|cffC2E8EB and |cffFF0202Hostile Units|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347A|cffC2E8EB] - Locate |cffFF0202Trolls|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347E|cffC2E8EB] - Locate |cffFF0202Hostile Animals|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347Q|cffC2E8EB] - Locate |cff1FBF00Elk|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347R|cffC2E8EB] - Locate |cff1FBF00Elk|r|cffC2E8EB and |cffFF0202Hostile Units|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347R|cffC2E8EB] - Locate |cffFE890DHostile Building|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347S|cffC2E8EB] - Locate |cffE45AAFLiving Clay|r': 'btnspy.png',
    '|cffC2E8EB[|cffFF6347W|cffC2E8EB] - Locate |cff1BE5B8Hawk|r': 'btnspy.png',
    '|cffC2E8EB[|r|cffFF6347B|r|cffC2E8EB] - Buildings Craft Recipe|r': 'btnbasicstruct.png',
    '|cffC2E8EB[|r|cffFF6347C|r|cffC2E8EB] - Magic Resistance|r': 'btnthickfur.png',
    '|cffC2E8EB[|r|cffFF6347C|r|cffC2E8EB] - Melt Herbs|r': 'btnunstableconcoction.png',
    '|cffC2E8EB[|r|cffFF6347C|r|cffC2E8EB] - More Forge Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347C|r|cffC2E8EB] - More Witch Doctors Hut Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347D|r|cffC2E8EB] - Activate Replenish Health|r': 'btnholybolt.png',
    '|cffC2E8EB[|r|cffFF6347D|r|cffC2E8EB] - Activate Soul Rend|r': 'btnshamanadept.png',
    '|cffC2E8EB[|r|cffFF6347D|r|cffC2E8EB] - Eat Corpse|r': 'ATCCannibalize.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - Armor Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - More Armory Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - More Workshop Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347F|r|cffC2E8EB] - Special Herb Quick Make Page|r': 'BTNRightBook.png',
    '|cffC2E8EB[|r|cffFF6347R|r|cffC2E8EB] - Ensnare (Ensnare Trap)|r': 'ATCEnsnare.png',
    '|cffC2E8EB[|r|cffFF6347R|r|cffC2E8EB] - Ensnare|r': 'ATCEnsnare.png',
    '|cffC2E8EB[|r|cffFF6347R|r|cffC2E8EB] - Spiked Net|r': 'BTNSpikedNet.png',
    '|cffC2E8EB[|r|cffFF6347R|r|cffC2E8EB] - Tele-Steal Food|r': 'BTNTeleStealMeat.png',
    '|cffC2E8EB[|r|cffFF6347W|r|cffC2E8EB] - Verdant Song|r': 'BTNVerdantSong.png',
    '|cffC2E8EBSpiritual Guidance|r': 'PASBTNSpiritualGuidance.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Alchemist|r': 'BTNAlchemist.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Assassin|r': 'btndarktrolltrapper.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Booster|r': 'btnforesttrollshadowpriest.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Contortionist|r': 'BTNContortionist.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Dementia Master|r': 'btndarktrollshadowpriest.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Dire Bear|r': 'btngrizzlybear.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Dire Wolf|r': 'btndirewolf.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Dreamwalker|r': 'BTNHypnotist.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Druid|r': 'BTNDruidoftheClawForestTrollIconV1.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Elementalist|r': 'btnicetrollshaman.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Escape Artist|r': 'btndarktroll.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Gurubashi Warrior|r': 'BTNTrollPredator.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Herb Master Gatherer|r': 'btnicetrollshadowpriest.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Hypnotist|r': 'BTNHypnotist.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Juggernaut|r': 'BTNTrollPredator.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Master Healer|r': 'BTNMasterHealer.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Omnigatherer|r': 'BTNTerrorTroll.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Radar Gatherer|r': 'BTNTerrorTroll.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Rogue|r': 'btndarktroll.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Sage|r': 'btnforesttrollshadowpriest.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Shapeshifter|r': 'btnbearform.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Spy|r': 'btnforesttrolltrapper.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Telethief|r': 'BTNContortionist.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Tracker|r': 'btnicetroll.png',
    '|cffC2E8EBUpgrade into |r|cffFFD700Trapper|r': 'BTNTrapper.png',
    '|cffFFFC00Enduring Spirit|r': 'pasbtnreincarnation.png',
    'A Thief': 'BTNThiefPouch.png',
    'Acid Bomb': 'btnacidbomb.png',
    'Acquired Knowlede': 'btnnecromancermaster.png',
    'Advanced Item Radar': 'btnspy.png',
    'Advanced Scout Radar': 'btnspy.png',
    'AMgq:ANcl': 'btnmammoth.png',
    'AMgs:ANcl': 'btnmammoth.png',
    'AMgt:ANcl': 'btnmammoth.png',
    'AMjf:AUsl': 'btnelunesblessing.png',
    'Anabolic Potion': 'btnpotionred.png',
    'Anchor Soul': 'btnresurrection.png',
    'Angelic Elemental': 'btndivineintervention.png',
    'Anger': 'btnunholyfrenzy.png',
    'Animal Training': 'BTNAnimalTraining.png',
    'Anti-Magic Potion': 'btnpotionofclarity.png',
    'Anti-Magic Shell': 'btnantimagicshell.png',
    'Arcane Interference': 'BTNArcaneInterference.png',
    'Assassin Spells': 'btntome.png',
    'Aura Dummy: |cff1775CC0 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC1 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC10 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC2 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC3 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC4 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC5 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC6 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC7 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC8 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1775CC9 Magic Resist|r': 'btnresistmagic.png',
    'Aura Dummy: |cff1FBF00Damage Reduction|r': 'btnhardenedskin.png',
    'Aura Dummy: |cff1FBF00Food dietary bonus.|r': 'btnmonsterlure.png',
    'Aura Dummy: |cff1FBF00Lesser Restoration|r': 'BTNRenew.png',
    'Aura Dummy: |cff1FBF00Makrura Carapace|r': 'BTNMakruraCarapace.png',
    'Aura Dummy: |cff1FBF00Makrura Cuirass|r': 'btnnagaarmorup3.png',
    'Aura Dummy: |cff1FBF00Snake Reflexes|r': 'BTNWindSerpentPassive.png',
    'Aura Dummy: |cff1FBF00Spell Damage Reduction|r': 'btnthickfur.png',
    'Aura Dummy: |cff1FBF00Thick Fur|r': 'BTNFrostBearPassive.png',
    'Aura Dummy: |cff1FBF00Thrill of the Hunt|r': 'BTNPantherPassive.png',
    'Aura Dummy: |cff1FBF00Wolf Voracity|r': 'BTNTimberWolfPassive.png',
    'Aura Dummy: Damage Reduction': 'btnhardenedskin.png',
    'Aura Dummy: Food dietary bonus.': 'btnmonsterlure.png',
    'Aura Dummy: Frost Cloak Caster': 'BTNCloakOfFrost.png',
    'Aura Dummy: Frost Cloak Target': 'BTNFrostBearPassive.png',
    'Aura Dummy: Lesser Restoration': 'BTNRenew.png',
    'Aura Dummy: Makrura Carapace': 'BTNMakruraCarapace.png',
    'Aura Dummy: Makrura Cuirass': 'btnnagaarmorup3.png',
    'Aura Dummy: Random Hat': 'btnselectheroon.png',
    'Aura Dummy: Snake Reflexes': 'BTNWindSerpentPassive.png',
    'Aura Dummy: Snake Toxin': 'btnslowpoison.png',
    'Aura Dummy: Thick Fur': 'BTNFrostBearPassive.png',
    'Aura Dummy: Thrill of the Hunt': 'BTNPantherPassive.png',
    'Aura Dummy: Trophy Hide': 'BTNElkTrophyHide.png',
    'Aura Dummy: Wolf Voracity': 'BTNTimberWolfPassive.png',
    'Aura Dummy: Zap 1': 'btnstasistrap.png',
    'Aura Dummy: Zap 2': 'btnstasistrap.png',
    'Axe Throw': 'BTNAxeThrow.png',
    'Bark Skin': 'btnthornshield.png',
    'Bear': 'pasbtndrunkendodge.png',
    'Bear Trap': 'BTNBearTrap.png',
    'Bird of Prey': 'PASBTNBirdOfPrey.png',
    'Bone Tistle': 'btnthoriumranged.png',
    'Booster Spells': 'btnsorceressmaster.png',
    'Boss Rewards': 'btnmedalionofcourage.png',
    'Brambles': 'btnentanglingroots.png',
    'Bring Down': 'PASBTNBringDown.png',
    'Build Armory': 'BTNArmory.png',
    'Build Camp Fire': 'btnfire.png',
    'Build Ensnare Trap': 'btncop.png',
    'Build Forge': 'BTNForge.png',
    'Build Hatchery': 'btnsnowowl.png',
    'Build Mage Fire': 'btnfire.png',
    'Build Omnidefender': 'btnorctower.png',
    'Build Spirit Ward': 'btnabsorbmagic.png',
    'Build Storage Hut': 'BTNForestTrollHut1.png',
    'Build Tannery': 'btnpigfarm.png',
    'Build Teleport Beacon': 'btnenergytower.png',
    'Build Tent': 'BTNTent.png',
    'Build Troll Hut': 'btnspiritlodge.png',
    'Build Witch Doctor': 'btnvoodoolounge.png',
    'Build Workshop': 'BTNOrcLumberMill.png',
    'Camouflage': 'btnambush.png',
    'Cat': 'pasbtnevasion.png',
    'Chain Reveal': 'btnreveal.png',
    'Cyclone': 'btncyclone.png',
    'Cloak': 'BTNDarkTrollTrapperCloak.png',
    'Coconut': 'BTNCoconut.png',
    'Collect Meat': 'btnmonsterlure.png',
    'Cook and collect Meat': 'btnmonsterlure.png',
    'Cook Meat': 'btnmonsterlure.png',
    'Create Philosophers': 'btnheartofsearinox.png',
    'Defensive Spells': 'btnmanual.png',
    'Dementia Inherited Spells': 'btnnecromanceradept.png',
    'Dementia Spells': 'btnnecromancermaster.png',
    'Dementia Summoning': 'pasbtngenericspellimmunity.png',
    'Depress': 'btnshadowpact.png',
    'Depression Aura': 'PASBTNShadowPact.png',
    'Devour': 'BTNLycanWolfBite.png',
    'Dire Bear Abilities': 'btnbearform.png',
    'Direwolf Abilities': 'btndirewolf.png',
    'Disease Potion': 'btnpotiongreen.png',
    'Dysentery Track AKA "Charlie Brown': 'BTNTracking.png',
    'Dream Stealer': 'BTNPASDoom.png',
    'Dream Vision': 'PASBTNDreamVision.png',
    'Dreamwalker Abilities': 'btnbookofthedead.png',
    'Drunk': 'btnlesserinvulneralbility.png',
    'Eagle Sight': 'PASBTNEagleSight.png',
    'Earth Guardians': 'btngolemstormbolt.png',
    'Elementalist Spells': 'btnmanual.png',
    'Empowered Axe Throw': 'BTNAxeThrowDW.png',
    'Endurance': 'btnheadhunterberserker.png',
    'Entangling Root Scroll': 'btnscrollofregenerationgreen.png',
    'Fervor Potion': 'btngreaterinvulneralbility.png',
    'Fetch': 'PASBTNFetchItem.png',
    'Find Clay Balls': 'btnthunderlizardegg.png',
    'Find Flints': 'btnstaffofsanctuary.png',
    'Find Mana Crystals': 'btnmanastone.png',
    'Find Mushrooms': 'BTNMushroom.png',
    'Find Sticks': 'btnnaturetouchgrow.png',
    'Find Stones': 'btngolemstormbolt.png',
    'Find Tinders': 'btnshimmerweed.png',
    'Firebolt': 'btnfirebolt.png',
    'Flame Spray': 'btnfirebolt.png',
    'Fortitude': 'pasbtndevotion.png',
    'Friend of the Hive': 'BTNFriendOfTheHive.png',
    'Full Heal': 'btnmarkoffire.png',
    'Gatherer Salves': 'btnbarrel.png',
    'Greater Hawk abilities': 'btntome.png',
    'Greater Reveal': 'btnreveal.png',
    'Grow Pet': 'BTNAdvanceLife.png',
    'Hatch': 'btnphoenixegg.png',
    'Hawk Eye': 'btnscout.png',
    'Hawk Inherited Spells': 'btntome.png',
    'Healing': 'btnhealingwave.png',
    'Healing Salve': 'BTNBronzeBowlFullGreen.png',
    'Healing wave': 'btnhealingwave.png',
    'Health Rejuv': 'btnreplenishhealth.png',
    'Hibernate': 'BTNAbility_Hibernation.png',
    'Hide Tracking Beacon': 'btnspy.png',
    'Hydra Claw Poison': 'btnimprovedstrengthofthewild.png',
    'Hypnosis': 'pasbtnelunesblessing.png',
    'Hypnotist Spells': 'btnbookofthedead.png',
    'Howl of Terror': 'BTNLoneWolf.png',
    'Item Radar': 'btnspy.png',
    'Item Warp': 'btnneutralmanashield.png',
    'Jealousy': 'btnsacrifice.png',
    'Juggernaut Inherited Spells': 'BTNTrollPredator.png',
    'Lesser Restoration': 'BTNRenew.png',
    'Lightning Shield': 'btnlightningshield.png',
    'Mage Inherited Spells': 'btnnecromanceradept.png',
    'Magic Mist': 'btncloudoffog.png',
    'Magical Evasion Spells': 'btnspellbookbls.png',
    'Make Temporary Mage Fire': 'btnfire.png',
    'Mana Rejuv': 'btnreplenishmana.png',
    'Maneuver': 'btndispelmagic.png',
    'Master Healer Spells': 'btnsorceressmaster.png',
    'Maximum Fervor': 'btnberserkfortrolls.png',
    'Meditate': 'BTNMedidate.png',
    'Melt a Native Herb': 'BTNYellowHerb.png',
    'Melt a River Root': 'btnwandofneutralization.png',
    'Melt a River Stem': 'btndotadepttraining.png',
    'Melt an Exotic Herb': 'BTNPurpleHerb.png',
    'Melt everything': 'btndizzy.png',
    'Mental quickness.': 'BTNContortionist.png',
    'Metronome': 'btnwandofmanasteal.png',
    'Mix Energy': 'btnmanadrain.png',
    'Mix Health': 'btnlifedrain.png',
    'Mix Heat': 'BTNHeatDrain.png',
    'Mix Herb': 'btnunstableconcoction.png',
    'Mud Hut Resilience': 'pasbtndevotion.png',
    'Nature': 'btnnaturetouchgrow.png',
    'Necromancer': 'btnskeletonwarrior.png',
    'Negative Blast': 'btnwandofshadowsight.png',
    'Nether Fade': 'btnbanish.png',
    'Night Stalker.': 'PASUNITWolf.png',
    'Oberserver Spells': 'btntome.png',
    'Offensive Spells': 'btnnecromanceradept.png',
    'OmniCure': 'btnbigbadvoodoospell.png',
    'Omnicure Potion': 'btnminorrejuvpotion.png',
    'Omnigatherer Inherited Spells': 'btntome.png',
    'Omnivore': 'BTNOmnivore.png',
    'Open Light Gate': 'btnsell.png',
    'Owl Gathering Radius': 'btnsnowowl.png',
    'Owl Health': 'btnsnowowl.png',
    'Owl Movement Radius': 'btnsnowowl.png',
    'Owl Speed': 'btnsnowowl.png',
    'Pack Up': 'btnpackbeast.png',
    'Pass Meat': 'BTNPassMeat6.png',
    'Pet Sleep': 'btnelunesblessing.png',
    'Pet Spells': 'BTNBeastCall.png',
    'Physical Evasion Spells': 'btnspellbookbls.png',
    'Poison': 'BTNPoisonFang.png',
    'Priest Inherited Spells': 'btnmanual.png',
    'Prowl': 'BTNPantherProwl.png',
    'Pump Up': 'btnbloodlust.png',
    'Query Tracking Beacon': 'btnspy.png',
    'Quick make Acid Bomb': 'btnacidbomb.png',
    'Quick make Anabolic Boots': 'btnwirtsotherleg.png',
    'Quick make Anabolic Potion': 'btnpotionred.png',
    'Quick make Anti-Magic Potion': 'btnpotionofclarity.png',
    'Quick make Armory Kit': 'BTNArmory.png',
    'Quick make Battle Armor': 'btnnagaarmorup2.png',
    'Quick make Battle Axe': 'btnorcmeleeupthree.png',
    'Quick make Battle Gloves': 'btnimprovedunholystrength.png',
    'Quick make Battle Shield': 'btnarcanitearmor.png',
    'Quick make Battle Staff': 'BTNBattleStaff.png',
    'Quick make Blow Gun': 'btnalleriaflute.png',
    'Quick make Bone Boots': 'BTNBoneBoots.png',
    'Quick make Bone Coat': 'BTNBoneCoat.png',
    'Quick make Bone Gloves': 'btngauntletsofogrepower.png',
    'Quick make Bone Shield': 'btnimprovedunholyarmor.png',
    'Quick make Boots of Bear': 'BTNBootsOfBearTenacity.png',
    'Quick make Boots of Wolf': 'BTNBootsOfWolfStamina.png',
    'Quick make Camp Fire Kit': 'btnfire.png',
    'Quick make Chameleon Hatchet': 'BTNChameleonHatchetStr.png',
    'Quick make Claws of Wolf': 'BTNWolfSBloodlustClaws.png',
    'Quick make Cloak Of Flames': 'BTNCloakOfInferno.png',
    'Quick make Cloak Of Frost': 'BTNCloakOfFrost.png',
    'Quick make Cloak Of Healing': 'BTNCloakOfHealing.png',
    'Quick make Cloak Of Mana': 'BTNCloakOfMana.png',
    'Quick make Coat of Bear': 'BTNCoatOfBearPresence.png',
    'Quick make Coat of Wolf': 'BTNChestOfWolfVoracity.png',
    'Quick make Cure All': 'btnlesserclaritypotion.png',
    'Quick make Dark Spear': 'btnarcaniteranged.png',
    'Quick make Dark Thistles': 'btnquillspray.png',
    'Quick make Disease Potion': 'btnpotiongreen.png',
    'Quick make Drunks Potion': 'btnlesserinvulneralbility.png',
    'Quick make Elk Skin Boots': 'BTNElkHideBoots.png',
    'Quick make Elk Skin Coat': 'BTNElkHideCoat.png',
    'Quick make Elk Skin Gloves': 'BTNElkHideGloves.png',
    'Quick make EMP': 'btnwispsplode.png',
    'Quick make Ensnare Trap': 'btncop.png',
    'Quick make Fervor Potion': 'btngreaterinvulneralbility.png',
    'Quick make Fire Bomb': 'btnliquidfire.png',
    'Quick make Forge Kit': 'BTNForge.png',
    'Quick make Greater Essence': 'BTNPurpleEssence.png',
    'Quick make Healing Potion': 'btnlesserrejuvpotion.png',
    'Quick make Healing Salve': 'BTNBronzeBowlFullGreen.png',
    'Quick make Hydra Scale Coat': 'btnnagaarmorup3.png',
    'Quick make Hydra Scale Gloves': 'btnimprovedstrengthofthewild.png',
    'Quick make Hunting Net': 'BTNHuntingNet.png',
    'Quick make Iron Axe': 'btnorcmeleeuptwo.png',
    'Quick make Iron Boots': 'btnboots.png',
    'Quick make Iron Coat': 'btnimprovedmoonarmor.png',
    'Quick make Iron Gloves': 'BTNIronGloves.png',
    'Quick make Iron Ingot': 'BTNIronIngot.png',
    'Quick make Iron Shield': 'btnhumanarmorupone.png',
    'Quick make Iron Spear': 'btnstrengthofthemoon.png',
    'Quick make Iron Staff': 'btnwand.png',
    'Quick make Jungle Bear Skin Boots': 'BTNBearHideBoots.png',
    'Quick make Jungle Bear Skin Coat': 'BTNBearHideCoat.png',
    'Quick make Jungle Bear Skin Gloves': 'BTNBearHideGloves.png',
    'Quick make Jungle Wolf Skin Boots': 'BTNWolfHideBoots.png',
    'Quick make Jungle Wolf Skin Coat': 'BTNWolfHideCoat.png',
    'Quick make Jungle Wolf Skin Gloves': 'BTNWolfHideGloves.png',
    'Quick make Lesser Essence': 'BTNOrangeEssence.png',
    'Quick make Living Clay': 'BTNGreenSentryWard.png',
    'Quick make Magic': 'btnmoonstone.png',
    'Quick make Magic Tree Seed': 'btnacorn.png',
    'Quick make Mana Crystal': 'BTNManaCrystal.png',
    'Quick make Mana Potion': 'btnpotionbluesmall.png',
    'Quick make Necromancer': 'BTNSkullShroudGlowIncreased.png',
    'Quick make Nether Potion': 'btnpotionofomniscience.png',
    'Quick make Nets': 'btnensnare.png',
    'Quick make Omnitower Kit': 'btnorctower.png',
    'Quick make Paws of Bear': 'BTNBearGlovesOfGreed.png',
    'Quick make Poison': 'btnhealingsalve.png',
    'Quick make Poison Spear': 'btnenvenomedspear.png',
    'Quick make Poison Thistles': 'BTNPoisonQuill.png',
    'Quick make Robe of the Magi': 'btnrobeofthemagi.png',
    'Quick make Scroll Of Cyclone': 'btnbansheemaster.png',
    'Quick make Scroll Of Entangling Root': 'btnscrollofregenerationgreen.png',
    'Quick make Scroll Of Fireball': 'btnscrollofhealing.png',
    'Quick make Scroll Of Living Dead': 'btnsnazzyscroll.png',
    'Quick make Scroll Of Stone Armor': 'btnscrolluber.png',
    'Quick make Scroll Of Swiftness': 'btnscrollofhaste.png',
    'Quick make Scroll Of Tsunami': 'btnsnazzyscrollpurple.png',
    'Quick make Shield': 'btnsteelarmor.png',
    'Quick make Smoke Bomb': 'BTNSmokepot.png',
    'Quick make Spirit Of Darkness': 'btnorbofdarkness.png',
    'Quick make Spirit Of Water': 'btnorboffrost.png',
    'Quick make Spirit Of Wind': 'btnorboflightning.png',
    'Quick make Spirit Ward': 'btnabsorbmagic.png',
    'Quick make Steel Axe': 'btnspiritwalkeradepttraining.png',
    'Quick make Steel Boots': 'BTNSteelBoots.png',
    'Quick make Steel Coat': 'btnadvancedmoonarmor.png',
    'Quick make Steel Gloves': 'btnadvancedunholystrength.png',
    'Quick make Steel Ingot': 'BTNSteelIngot.png',
    'Quick make Steel Shield': 'btnthoriumarmor.png',
    'Quick make Steel Spear': 'btnthoriumranged.png',
    'Quick make Tannery Kit': 'btnpigfarm.png',
    'Quick make Teleport Beacon Kit': 'btnenergytower.png',
    'Quick make Tent Kit': 'BTNTent.png',
    'Quick make Transport Ship': 'btnnightelftransport.png',
    'Quick make Troll Protector': 'BTNTrollProtector.png',
    'Quick make Venom Fang': 'BTNPoisonFang.png',
    'Quick make Witch Doctors Hut Kit': 'btnvoodoolounge.png',
    'Quick make Workshop Kit': 'BTNOrcLumberMill.png',
    'Radar Spells': 'btnspy.png',
    'Rage': 'btnheadhunterberserker.png',
    'Ranged heal': 'btnheal.png',
    'Ravenous Beast': 'btncannibalize.png',
    'Recipe: Healing Salve': 'btnhealingsalve.png',
    'Recipe: Hypnosis Salve': 'pasbtnelunesblessing.png',
    'Recipe: Poison Salve': 'btnvialempty.png',
    'Recipe: Speed Salve': 'btnpotionred.png',
    'Reduce Food': 'btnmonsterlure.png',
    'Reincarnation': 'btnreincarnation.png',
    'Release Pet': 'BTNReleasePet.png',
    'Replenish Energy': 'pasbtnregenerate.png',
    'Replenish Health': 'btnholybolt.png',
    'Rescue': 'BTNWing.png',
    'Restore Heat': 'btnwalloffire.png',
    'Restore Mana': 'btnneutralmanashield.png',
    'Reveal': 'btnreveal.png',
    'Rip and Tear': 'pasbtnghoulfrenzy.png',
    'Rogue abilities': 'btnspellbookbls.png',
    'Sage Inherited Spells': 'btnmanual.png',
    'Sage Spells': 'btnsorceressmaster.png',
    'Scroll of Haste': 'btnscrollofhaste.png',
    'Scroll of Living Dead': 'btnskeletonwarrior.png',
    'Self Preservation': 'btnregenerate.png',
    'Sentinel': 'btnsentinel.png',
    'Shadow Sight': 'PASBTNTrollSight.png',
    'Shapeshifter Forms': 'btnbearform.png',
    'Shield Charge': 'BTNShieldCharge.png',
    'Smoke Stream': 'btncloudoffog.png',
    'Snake Reflexes': 'BTNWindSerpentPassive.png',
    'Snake Toxin': 'btnslowpoison.png',
    'Sniff': 'BTNPoisonousSmell.png',
    'Spear Cast (Stone)': 'btnthoriumranged.png',
    'Spy Inherited Spells': 'btntome.png',
    'Spirit Link': 'btnspiritlink.png',
    'Spirit Prison': 'btnwitchdoctormaster.png',
    'Spiritual Guidance': 'PASBTNSpiritualGuidance.png',
    'Stash Meat.': 'BTNFeedPet.png',
    'Steal': 'btnpickupitem.png',
    'Steal Food': 'BTNStealMeat.png',
    'Subclass Menu': 'btnstatup.png',
    'Summon |cff00EAFFLez|r Rune': 'BTNLezRune.png',
    'Summon |cff1FBF00Nel|r Rune': 'BTNNelRune.png',
    'Summon |cffFF0202Ka|r Rune': 'BTNKaRune.png',
    'Summon Ka Rune': 'BTNKaRune.png',
    'Summon Lez Rune': 'BTNLezRune.png',
    'Summon Nel Rune': 'BTNNelRune.png',
    'Swoop': 'PASBTNSWoopEnemy.png',
    'Tame Pet': 'BTNTamePet.png',
    'Telefeed': 'BTNTeleFeedMeat.png',
    'Teleport Mirror': 'btnwispsplode.png',
    'Telethief Abilities': 'btnspellbookbls.png',
    'Thick Fur': 'BTN_Misc_Pelt_Bear_01.png',
    'Thieve': 'btnspellbookbls.png',
    'Thrill of Battle': 'BTNThrillOfBattle.png',
    'Toggle Pet Control': 'btnselectunit.png',
    'Tower Item Dummy Cast Enemy': 'btnstag.png',
    'Track': 'ATCTrack.png',
    'Tracking Trap': 'btnstasistrap.png',
    'Transform (Bear)': 'btngrizzlybear.png',
    'Transform (Panther)': 'BTNPanther.png',
    'Transform (Tiger)': 'BTNTiger.png',
    'Transform (Wolf)': 'btndirewolf.png',
    'Trap Toolkit': 'btnpackbeast.png',
    'Troll Protector Aura': 'pasbtndevotion.png',
    'Troll Targeting': 'ATCTrack.png',
    'True Sight': 'pasbtngyrocoptertruesight.png',
    'Undying': 'BTNUndying.png',
    'Upgrade into Alchemist': 'BTNAlchemist.png',
    'Upgrade into Assassin': 'BTNDarkTrollTrapperCloak.png',
    'Upgrade into Booster': 'btnforesttrollshadowpriest.png',
    'Upgrade into Contortionist': 'BTNContortionist.png',
    'Upgrade into Dire Bear': 'btngrizzlybear.png',
    'Upgrade into Dreamwalker': 'BTNHypnotist.png',
    'Upgrade into Druid': 'BTNDruidoftheClawForestTrollIconV1.png',
    'Upgrade into Elementalist': 'btnicetrollshaman.png',
    'Upgrade into Escape Artist': 'BTNDarkTrollTrapperCloak.png',
    'Upgrade into Gurubashi Warrior': 'BTNTrollPredator.png',
    'Upgrade into Herb Master Gatherer': 'btnicetrollshadowpriest.png',
    'Upgrade into Hypnotist': 'BTNHypnotist.png',
    'Upgrade into Juggernaut': 'BTNTrollPredator.png',
    'Upgrade into Master Healer': 'BTNMasterHealer.png',
    'Upgrade into Omnigatherer': 'BTNTerrorTroll.png',
    'Upgrade into Radar Gatherer': 'BTNTerrorTroll.png',
    'Upgrade into Rogue': 'BTNDarkTrollTrapperCloak.png',
    'Upgrade into Sage': 'btnforesttrollshadowpriest.png',
    'Upgrade into Spy': 'btnforesttrolltrapper.png',
    'Upgrade into Telethief': 'BTNContortionist.png',
    'Upgrade into Tracker': 'btnicetroll.png',
    'Upgrade into Trapper': 'BTNTrapper.png',
    'Vicious Strike Attack trigger': 'PASBTNViciousStrike.png',
    'Vicious Strikes True spell': 'PASBTNViciousStrike.png',
    'Voracious Bear': 'BTNHungryBear.png',
    'Way of the Hawk': 'btnnecromanceradept.png',
    'Way of the Tracker': 'btnnecromanceradept.png',
    'Ward the Area': 'BTNGreenSentryWard.png',
    'Warrior Skills': 'BTNTrollPredator.png',
    'Weapons of Choice': 'PASBTNWeaponsOfChoice.png',
    'Whirling Axes': 'BTNWhirlingAxes.png',
    'Wolf': 'btnvampiricaura.png',
    'Wolf Bite': 'BTNLycanWolfBite.png',
    'Wolf Life Steal': 'btndirewolf.png',
    'Wolf Voracity': 'BTNTimberWolfPassive.png',
    'WOLFS_BLOODLUST_CLAWS_BLOODLUST': 'btnbloodlust.png'
  },
  items: {
    'A Thief': 'BTNThiefPouch.png',
    'Acid Bomb': 'btnacidbomb.png',
    'Anabolic Boots': 'btnwirtsotherleg.png',
    'Anabolic Potion': 'btnpotionred.png',
    'Anti-Magic Potion': 'btnpotionofclarity.png',
    'Armory Kit': 'BTNArmory.png',
    'Arms Slot': 'PASBTNWeaponsOfChoiceSlot.png',
    'Athelas Seed': 'BTNGreenSeed.png',
    'Banana': 'BTNBanana.png',
    'Basic Shield': 'btnsteelarmor.png',
    'Battle Armor': 'btnnagaarmorup2.png',
    'Battle Axe': 'btnorcmeleeupthree.png',
    'Battle Gloves': 'btnimprovedunholystrength.png',
    'Battle Shield': 'btnarcanitearmor.png',
    'Battle Staff': 'BTNBattleStaff.png',
    'Bear Hide': 'BTNBearHide.png',
    'Bear Skin Boots': 'BTNBearHideBoots.png',
    'Bear Skin Coat': 'BTNBearHideCoat.png',
    'Bear Skin Gloves': 'BTNBearHideGloves.png',
    'Bee Hive': 'BTNBeehive.png',
    'Blow Gun': 'btnalleriaflute.png',
    'Bone': 'BTNBone.png',
    'Bone Boots': 'BTNBoneBoots.png',
    'Bone Coat': 'BTNBoneCoat.png',
    'Bone Gloves': 'btngauntletsofogrepower.png',
    'Bone Shield': 'btnimprovedunholyarmor.png',
    'Boots of Bear': 'BTNBootsOfBearTenacity.png',
    'Boots of Wolfs Stamina': 'BTNBootsOfWolfStamina.png',
    'Camp Fire Kit': 'btnfire.png',
    'Chameleon Hatchet': 'BTNChameleonHatchetStr.png',
    'Clay Ball': 'btnthunderlizardegg.png',
    'Clay Explosion': 'BTNGreenSentryWard.png',
    'Claws of Wolf': 'BTNWolfSBloodlustClaws.png',
    'Cloak of Flames': 'BTNCloakOfInferno.png',
    'Cloak of Frost': 'BTNCloakOfFrost.png',
    'Cloak of Healing': 'BTNCloakOfHealing.png',
    'Cloak of Mana': 'BTNCloakOfMana.png',
    'Coat of bear': 'BTNCoatOfBearPresence.png',
    'Coat of Wolf': 'BTNChestOfWolfVoracity.png',
    'Coconut': 'BTNCoconut.png',
    'Cooked Meat': 'btnmonsterlure.png',
    'Cure Potion': 'btnlesserclaritypotion.png',
    'Dark Spear': 'BTNDarkSpearTrapper.png',
    'Dark Thistles': 'btnquillspray.png',
    'Disc0-Duck': 'btnheartofaszune.png',
    'Disease Potion': 'btnpotiongreen.png',
    'Drunk': 'btnlesserinvulneralbility.png',
    'Eat raw meat.': 'btncannibalize.png',
    'Elk Hide': 'BTNElkHide.png',
    'Elk Skin Boots': 'BTNElkHideBoots.png',
    'Elk Skin Coat': 'BTNElkHideCoat.png',
    'Elk Skin Gloves': 'BTNElkHideGloves.png',
    'EMP': 'btnwispsplode.png',
    'Empowered Necromancer': 'BTNSavageGladiatorChain.png',
    'Ensnare Trap Kit': 'btncop.png',
    'Essence Of Bees': 'BTNBeehive.png',
    'Fervor Potion': 'btngreaterinvulneralbility.png',
    'Fire Bomb': 'btnliquidfire.png',
    'Flint': 'btnstaffofsanctuary.png',
    'Food Slot.': 'BTNBearFoodSlot.png',
    'Forge Kit': 'BTNForge.png',
    'Gem of Knowledge': 'btnenchantedgemstone.png',
    'Greater Essence': 'BTNPurpleEssence.png',
    'Happy Food Supplies': 'BTNBearFoodSlot.png',
    'Hatchery Kit': 'btnsnowowl.png',
    'Hawk Egg': 'btnphoenixegg.png',
    'Healing Potion': 'btnlesserrejuvpotion.png',
    'Healing Salve': 'BTNBronzeBowlFullGreen.png',
    'Hydra Claws': 'btnimprovedstrengthofthewild.png',
    'Hydra Hint': 'btnsorceressmaster.png',
    'Hydra Scale Coat': 'btnnagaarmorup3.png',
    'Hypnosis Salve': 'pasbtnelunesblessing.png',
    'Honeycomb': 'BTNHoneycomb.png',
    'Horn Of the Mammoth': 'btnhornoffog.png',
    'Hunter': 'BTNTrophyHideDummy.png',
    'Hunting Net': 'BTNHuntingNet.png',
    'Iron Axe': 'btnorcmeleeuptwo.png',
    'Iron Boots': 'btnboots.png',
    'Iron Coat': 'btnimprovedmoonarmor.png',
    'Iron Gloves': 'BTNIronGloves.png',
    'Iron Ingot': 'BTNIronIngot.png',
    'Iron Shield': 'btnhumanarmorupone.png',
    'Iron Spear': 'btnstrengthofthemoon.png',
    'Iron Staff': 'btnwand.png',
    'Leaf of Blue Herb': 'BTNBlueHerb.png',
    'Leaf of Exotic Herb': 'BTNPurpleHerb.png',
    'Leaf of Native Herb': 'BTNYellowHerb.png',
    'Leaf of Orange Herb': 'BTNOrangeHerb.png',
    'Lesser Essence': 'BTNOrangeEssence.png',
    'Living Clay': 'BTNGreenSentryWard.png',
    'Mage': 'btnnecromancermaster.png',
    'Mage Fire Kit': 'btnfire.png',
    'Mage Masher': 'btnspiritwalkermastertraining.png',
    'Magic': 'btnmoonstone.png',
    'Magic Palm Tree Seed': 'btnacorn.png',
    'Makrura Carapace': 'BTNMakruraCarapace.png',
    'Makrura Claw': 'BTNMakruraClaws.png',
    'Makruru Cuirass': 'btnnagaarmorup3.png',
    'Mana Crystal': 'btnmanastone.png',
    'Mana Potion': 'btnpotionbluesmall.png',
    'Materials Slot': 'BTNResourcesPack.png',
    'Medalion of the Thief': 'btnmedalionofcourage.png',
    'Medallion of Courage': 'btnmedalionofcourage.png',
    'Mushroom': 'BTNMushroom.png',
    'Necromancer': 'BTNSkullShroudGlowIncreased.png',
    'Net': 'btnensnare.png',
    'Nether Potion': 'btnpotionofomniscience.png',
    'Omnicure Potion': 'btnminorrejuvpotion.png',
    'Omnitower Kit': 'btnorctower.png',
    'Panther Fang': 'BTNPantherFang.png',
    'Paws of Bear': 'BTNBearGlovesOfGreed.png',
    'Philosopher': 'btnheartofsearinox.png',
    'Poison': 'BTNPoisonFang.png',
    'Poison Spear': 'BTNPoisonSpear.png',
    'Poison Thistles': 'BTNPoisonQuill.png',
    'River Root': 'btnwandofneutralization.png',
    'River Stem': 'btndotadepttraining.png',
    'Robe of the Magi': 'btnrobeofthemagi.png',
    'Scale': 'btnnagaarmorup1.png',
    'Scavenged Mushroom': 'BTNMushroom.png',
    'Scroll of Cyclone': 'btnbansheemaster.png',
    'Scroll of Entangling Roots': 'btnscrollofregenerationgreen.png',
    'Scroll of Fire Ball': 'btnscrollofhealing.png',
    'Scroll of Haste': 'btnscrollofhaste.png',
    'Scroll of Living Dead': 'btnsnazzyscroll.png',
    'Scroll of Stone Shield': 'btnscrolluber.png',
    'Scroll of Tsunami': 'btnsnazzyscrollpurple.png',
    'Scroll Slot': 'PASBTNScrollSlot.png',
    'Smoke Bomb': 'BTNSmokepot.png',
    'Spirit Of Darkness': 'btnorbofdarkness.png',
    'Spirit Of Water': 'btnorboffrost.png',
    'Spirit Of Wind': 'btnorboflightning.png',
    'Spirit Ward Kit': 'btnabsorbmagic.png',
    'Staff of Wisdom': 'btnspiritwalkeradepttraining.png',
    'Stashed raw meat': 'BTNFeedPet.png',
    'Steel Axe': 'btnspiritwalkeradepttraining.png',
    'Steel Boots': 'BTNSteelBoots.png',
    'Steel Coat': 'btnadvancedmoonarmor.png',
    'Steel Gloves': 'btnadvancedunholystrength.png',
    'Steel Ingot': 'BTNSteelIngot.png',
    'Steel Shield': 'btnthoriumarmor.png',
    'Steel Spear': 'btnthoriumranged.png',
    'Stick': 'btnnaturetouchgrow.png',
    'Stone': 'btngolemstormbolt.png',
    'Stone Axe': 'btnorcmeleeupone.png',
    'Stone Spear': 'btnsteelranged.png',
    'Storage Hut Kit': 'BTNForestTrollHut1.png',
    'Tannery Kit': 'btnpigfarm.png',
    'Teleport beacon Kit': 'btnenergytower.png',
    'Tent Kit': 'BTNTent.png',
    'Thistles': 'btnquillsprayoff.png',
    'Tinder': 'btnshimmerweed.png',
    'Transport Ship Kit': 'btnnightelftransport.png',
    'Troll Hut Kit': 'btnspiritlodge.png',
    'Troll Protector': 'BTNTrollProtector.png',
    'Twin Island Potion': 'btnpotiongreensmall.png',
    'Ultra Poison': 'BTNUltraPoisonSpear.png',
    'Ultra Poison Spear': 'BTNUltraPoisonSpear.png',
    'Venom Fang': 'BTNPoisonFang.png',
    'Witch Doctors Hut Kit': 'btnvoodoolounge.png',
    'Wolf Hide': 'BTNWolfHide.png',
    'Wolf Skin Boots': 'BTNWolfHideBoots.png',
    'Wolf Skin Coat': 'BTNWolfHideCoat.png',
    'Wolf Skin Gloves': 'BTNWolfHideGloves.png',
    'Workshop Kit': 'BTNOrcLumberMill.png'
  },
  buildings: {

  },
  trolls: {

  },
  units: {
    'Alchemist': 'BTNAlchemist.png',
    'Armory': 'BTNArmory.png',
    'Assassin': 'BTNDarkTrollTrapperCloak.png',
    'Athelas Bush': 'btnacorn.png',
    'Bear Form': 'btngrizzlybear.png',
    'Beastmaster': 'BTNShaman.png',
    'Bee Hive': 'BTNBeehive.png',
    'Blue Herb': 'btnacorn.png',
    'Booster': 'btnforesttrollshadowpriest.png',
    'Contortionist': 'BTNContortionist.png',
    'Dire Bear': 'btngrizzlybear.png',
    'Dreamwalker': 'BTNHypnotist.png',
    'Druid': 'BTNDruidoftheClawForestTrollIconV1.png',
    'Elder Panther': 'BTNPanther.png',
    'Elementalist': 'btnicetrollshaman.png',
    'Escape Artist': 'BTNDarkTrollTrapperCloak.png',
    'Forge': 'BTNForge.png',
    'Gatherer': 'BTNGatherer.png',
    'Gurubashi Champion': 'BTNTrollPredator.png',
    'Gurubashi Warrior': 'btnheadhunterberserker.png',
    'Herb Master': 'btnicetrollshadowpriest.png',
    'Hidden Stash': 'btnacorn.png',
    'Hypnotist': 'BTNHypnotist.png',
    'Hunter': 'btnforesttroll.png',
    'Yellow Herb': 'btnacorn.png',
    'Living Clay': 'BTNGreenSentryWard.png',
    'Mage': 'btnwitchdoctor.png',
    'Master Healer': 'BTNMasterHealer.png',
    'Mushroom Colony': 'btnacorn.png',
    'Omni Gatherer': 'BTNTerrorTroll.png',
    'Omnitower': 'btnorctower.png',
    'Orange Herb': 'btnacorn.png',
    'Panther': 'BTNPanther.png',
    'Panther Form': 'BTNPanther.png',
    'Priest': 'btnshadowhunter.png',
    'Purple Herb': 'btnacorn.png',
    'Radar Gatherer': 'BTNTerrorTroll.png',
    'Random Troll |cffffcc00(D)|r': 'btnselectheroon.png',
    'Rogue': 'BTNDarkTrollTrapperCloak.png',
    'Sage': 'btnforesttrollshadowpriest.png',
    'Scout': 'BTNTrollScout.png',
    'Snake': 'BTNWindSerpentPassive.png',
    'Spy': 'btnforesttrolltrapper.png',
    'Storage Hut': 'BTNForestTrollHut1.png',
    'Tannery': 'btnpigfarm.png',
    'Telethief': 'BTNContortionist.png',
    'The One': 'btnheadhunterberserker.png',
    'Thief': 'BTNDarkTrollTrapperCloak.png',
    'Thistle Shrub': 'btnacorn.png',
    'Tiger Form': 'BTNTiger.png',
    'Track Trap': 'btnstasistrap.png',
    'Tracker': 'btnicetrollbeserker.png',
    'Trapper': 'BTNTrapper.png',
    'Uber Hive': 'BTNBeehive.png',
    'UDIR_10': 'BTNChestOfWolfVoracity.png',
    'UDIR_100': 'btnacorn.png',
    'UDIR_101': 'BTNForge.png',
    'UDIR_102': 'btnnightelftransport.png',
    'UDIR_103': 'BTNMakruraClaws.png',
    'UDIR_106': 'btnnaturetouchgrow.png',
    'UDIR_107': 'btnstaffofsanctuary.png',
    'UDIR_109': 'BTNMushroom.png',
    'UDIR_11': 'BTNBearHideCoat.png',
    'UDIR_110': 'btnthunderlizardegg.png',
    'UDIR_111': 'BTNElkHide.png',
    'UDIR_112': 'BTNWolfHide.png',
    'UDIR_113': 'BTNBearHide.png',
    'UDIR_114': 'BTNBone.png',
    'UDIR_115': 'btnmanastone.png',
    'UDIR_117': 'btnmoonstone.png',
    'UDIR_12': 'BTNCoatOfBearPresence.png',
    'UDIR_120': 'BTNPoisonQuill.png',
    'UDIR_121': 'btnphoenixegg.png',
    'UDIR_123': 'BTNIronIngot.png',
    'UDIR_124': 'BTNSteelIngot.png',
    'UDIR_125': 'btnorboflightning.png',
    'UDIR_126': 'BTNOrangeEssence.png',
    'UDIR_127': 'BTNPurpleEssence.png',
    'UDIR_128': 'btnorboffrost.png',
    'UDIR_13': 'BTNBoneCoat.png',
    'UDIR_132': 'btndotadepttraining.png',
    'UDIR_133': 'btnwandofneutralization.png',
    'UDIR_134': 'BTNGreenSeed.png',
    'UDIR_135': 'BTNBlueHerb.png',
    'UDIR_136': 'BTNOrangeHerb.png',
    'UDIR_137': 'BTNPurpleHerb.png',
    'UDIR_138': 'BTNYellowHerb.png',
    'UDIR_14': 'btnimprovedmoonarmor.png',
    'UDIR_140': 'BTNBronzeBowlFullGreen.png',
    'UDIR_142': 'btnpotiongreensmall.png',
    'UDIR_143': 'BTNHuntingNet.png',
    'UDIR_144': 'btnensnare.png',
    'UDIR_145': 'btnwand.png',
    'UDIR_146': 'BTNBattleStaff.png',
    'UDIR_15': 'btnadvancedmoonarmor.png',
    'UDIR_16': 'btnnagaarmorup3.png',
    'UDIR_17': 'btnnagaarmorup2.png',
    'UDIR_18': 'btnrobeofthemagi.png',
    'UDIR_19': 'btnnagaarmorup3.png',
    'UDIR_2': 'btnorcmeleeuptwo.png',
    'UDIR_21': 'btnacidbomb.png',
    'UDIR_22': 'btnpotionred.png',
    'UDIR_23': 'btnpotionofclarity.png',
    'UDIR_24': 'btnlesserclaritypotion.png',
    'UDIR_25': 'btnpotiongreen.png',
    'UDIR_26': 'btnlesserinvulneralbility.png',
    'UDIR_27': 'btnpotionbluesmall.png',
    'UDIR_28': 'btnpotionofomniscience.png',
    'UDIR_29': 'btnscrollofregenerationgreen.png',
    'UDIR_30': 'btnscrollofhealing.png',
    'UDIR_31': 'btnsnazzyscroll.png',
    'UDIR_32': 'btnscrolluber.png',
    'UDIR_33': 'btnscrollofhaste.png',
    'UDIR_34': 'btnsnazzyscrollpurple.png',
    'UDIR_35': 'btnbansheemaster.png',
    'UDIR_36': 'BTNGreenSentryWard.png',
    'UDIR_37': 'BTNElkHideBoots.png',
    'UDIR_38': 'BTNWolfHideBoots.png',
    'UDIR_39': 'BTNBootsOfWolfStamina.png',
    'UDIR_4': 'btnorcmeleeupthree.png',
    'UDIR_40': 'BTNBearHideBoots.png',
    'UDIR_41': 'BTNBootsOfBearTenacity.png',
    'UDIR_42': 'BTNBoneBoots.png',
    'UDIR_43': 'btnboots.png',
    'UDIR_44': 'BTNSteelBoots.png',
    'UDIR_45': 'btnwirtsotherleg.png',
    'UDIR_47': 'BTNChameleonHatchetStr.png',
    'UDIR_48': 'BTNChameleonHatchetAgi.png',
    'UDIR_49': 'BTNChameleonHatchetInt.png',
    'UDIR_5': 'btnspiritwalkermastertraining.png',
    'UDIR_50': 'BTNCloakOfInferno.png',
    'UDIR_51': 'BTNCloakOfHealing.png',
    'UDIR_52': 'BTNCloakOfMana.png',
    'UDIR_53': 'BTNCloakOfFrost.png',
    'UDIR_54': 'BTNSkullShroudGlowIncreased.png',
    'UDIR_55': 'BTNSavageGladiatorChain.png',
    'UDIR_56': 'BTNElkHideGloves.png',
    'UDIR_57': 'BTNWolfHideGloves.png',
    'UDIR_58': 'BTNWolfSBloodlustClaws.png',
    'UDIR_59': 'BTNBearHideGloves.png',
    'UDIR_60': 'BTNBearGlovesOfGreed.png',
    'UDIR_62': 'btngauntletsofogrepower.png',
    'UDIR_63': 'BTNIronGloves.png',
    'UDIR_64': 'btnadvancedunholystrength.png',
    'UDIR_65': 'btnimprovedunholystrength.png',
    'UDIR_66': 'btnimprovedstrengthofthewild.png',
    'UDIR_68': 'btnhornoffog.png',
    'UDIR_69': 'btnsteelarmor.png',
    'UDIR_7': 'btnlesserrejuvpotion.png',
    'UDIR_70': 'btnimprovedunholyarmor.png',
    'UDIR_71': 'btnhumanarmorupone.png',
    'UDIR_72': 'btnthoriumarmor.png',
    'UDIR_74': 'BTNMakruraCarapace.png',
    'UDIR_75': 'BTNTrollProtector.png',
    'UDIR_76': 'btnsteelranged.png',
    'UDIR_77': 'btnstrengthofthemoon.png',
    'UDIR_78': 'btnthoriumranged.png',
    'UDIR_8': 'BTNElkHideCoat.png',
    'UDIR_81': 'BTNUltraPoisonSpear.png',
    'UDIR_82': 'BTNArmory.png',
    'UDIR_86': 'BTNTent.png',
    'UDIR_89': 'BTNForestTrollHut1.png',
    'UDIR_9': 'BTNWolfHideCoat.png',
    'UDIR_92': 'btnorctower.png',
    'UDIR_94': 'btnpigfarm.png',
    'UDIR_95': 'BTNOrcLumberMill.png',
    'UDIR_97': 'btnvoodoolounge.png',
    'Water Herb': 'btnacorn.png',
    'Witch Doctor': 'btnvoodoolounge.png',
    'Workshop': 'BTNOrcLumberMill.png'
  },
};

export function resolveExplicitIcon(category: ITTIconCategory, key: string): string | undefined {
  // First, check the requested category
  const table = ICON_MAP[category];
  const filename = table[key];
  
  if (!filename) {
    // If not found in requested category, search all categories
    const allCategories: ITTIconCategory[] = ['abilities', 'items', 'buildings', 'trolls', 'units'];
    for (const cat of allCategories) {
      const catTable = ICON_MAP[cat];
      const foundFilename = catTable[key];
      if (foundFilename) {
        // Found the mapping, now determine which directory the file is in
        return findIconPath(foundFilename);
      }
    }
    return undefined;
  }
  
  // Found in requested category, determine which directory the file is actually in
  return findIconPath(filename);
}

/**
 * Finds the actual directory path for an icon filename.
 * Since icons can be shared across categories, we check which category
 * has this filename mapped and prefer items directory for shared icons.
 */
function findIconPath(filename: string): string {
  const allCategories: ITTIconCategory[] = ['items', 'abilities', 'buildings', 'trolls', 'units'];
  
  // Check each category to see if this filename is mapped there
  // Priority: items first (most shared icons are there), then others
  for (const cat of allCategories) {
    const catTable = ICON_MAP[cat];
    if (Object.values(catTable).includes(filename)) {
      return `/icons/itt/${cat}/${filename}`;
    }
  }
  
  // Fallback: if somehow not found, try items directory (most common)
  return `/icons/itt/items/${filename}`;
}

