"""Helper modules for the extraction toolkit."""

from .ability_extractor import (
    build_ability_output,
    collect_ability_files,
    extract_abilities,
    load_ability_descriptions,
)
from .ability_generator import (
    categorize_abilities,
    clean_description,
    create_category_files,
    create_index_file,
    create_types_file,
    escape_typescript_string,
    format_ability,
    generate_abilities,
    generate_and_write as generate_abilities_ts,
    load_abilities,
)
from .description_extractor import (
    extract_descriptions_from_directory,
    load_wurst_content,
    write_descriptions_to_file,
)
from .buildings_extractor import (
    build_buildings_output,
    extract_all_buildings,
    extract_and_write as extract_buildings,
    extract_building_from_file,
    extract_craftable_items,
    extract_unit_ids,
    write_buildings_to_file,
)
from .buildings_generator import (
    format_building,
    generate_and_write as generate_buildings,
    generate_buildings as generate_buildings_impl,
    generate_buildings_ts_content,
    load_buildings,
    write_buildings_ts,
)
from .classes_generator import (
    determine_parent_and_type,
    format_base_class,
    format_derived_class,
    generate_and_write as generate_classes,
    generate_classes as generate_classes_impl,
    generate_classes_ts_content,
    generate_derived_classes_ts_content,
    load_units,
    separate_classes,
    write_classes_files,
)
from .base_items_generator import (
    categorize_items,
    collect_all_items,
    determine_category,
    escape_typescript_string,
    format_item,
    format_item_name,
    generate_and_write as generate_base_items,
    generate_base_items as generate_base_items_impl,
    generate_category_file_content,
    load_item_stats,
    load_recipes,
    normalize_item_id,
    write_category_file,
)
from .external_items_generator import (
    collect_external_items,
    determine_category as determine_category_external,
    format_item as format_item_external,
    generate_and_write as generate_external_items,
    generate_external_items as generate_external_items_impl,
    generate_external_items_ts_content,
    get_existing_item_ids,
    load_recipes as load_recipes_external,
    normalize_item_id as normalize_item_id_external,
    write_external_items_ts,
)
from .item_stats_extractor import (
    collect_crafting_files,
    extract_all_item_stats,
    extract_and_write as extract_item_stats,
    extract_item_stats_from_file,
    write_item_stats_to_file,
)
from .recipes_extractor import (
    build_recipes_output,
    collect_recipe_files,
    extract_all_recipes,
    extract_and_write as extract_recipes,
    extract_item_ids,
    extract_unit_ids as extract_unit_ids_for_recipes,
    normalize_lines,
    parse_wurst_file,
    write_recipes_to_file,
)
from .units_extractor import (
    build_units_output,
    determine_unit_type,
    extract_all_units,
    extract_and_write as extract_units,
    extract_attribute_growth,
    extract_unit_ids as extract_unit_ids_for_units,
    extract_unit_stats,
    write_units_to_file,
)

__all__ = [
    "build_ability_output",
    "collect_ability_files",
    "extract_abilities",
    "load_ability_descriptions",
    "categorize_abilities",
    "clean_description",
    "create_category_files",
    "create_index_file",
    "create_types_file",
    "escape_typescript_string",
    "format_ability",
    "generate_abilities",
    "generate_abilities_ts",
    "load_abilities",
    "extract_descriptions_from_directory",
    "load_wurst_content",
    "write_descriptions_to_file",
    "collect_crafting_files",
    "extract_all_item_stats",
    "extract_item_stats",
    "extract_item_stats_from_file",
    "write_item_stats_to_file",
    "build_buildings_output",
    "extract_all_buildings",
    "extract_buildings",
    "extract_building_from_file",
    "extract_craftable_items",
    "extract_unit_ids",
    "write_buildings_to_file",
    "format_building",
    "generate_buildings",
    "generate_buildings_impl",
    "generate_buildings_ts_content",
    "load_buildings",
    "write_buildings_ts",
    "determine_parent_and_type",
    "format_base_class",
    "format_derived_class",
    "generate_classes",
    "generate_classes_impl",
    "generate_classes_ts_content",
    "generate_derived_classes_ts_content",
    "load_units",
    "separate_classes",
    "write_classes_files",
    "collect_external_items",
    "determine_category",
    "format_item",
    "generate_external_items",
    "generate_external_items_impl",
    "generate_external_items_ts_content",
    "get_existing_item_ids",
    "load_recipes",
    "normalize_item_id",
    "write_external_items_ts",
    "categorize_items",
    "collect_all_items",
    "escape_typescript_string",
    "format_item",
    "format_item_name",
    "generate_base_items",
    "generate_base_items_impl",
    "generate_category_file_content",
    "load_item_stats",
    "write_category_file",
    "build_units_output",
    "determine_unit_type",
    "extract_all_units",
    "extract_units",
    "extract_attribute_growth",
    "extract_unit_ids_for_units",
    "extract_unit_stats",
    "write_units_to_file",
    "build_recipes_output",
    "collect_recipe_files",
    "extract_all_recipes",
    "extract_recipes",
    "extract_item_ids",
    "extract_unit_ids_for_recipes",
    "normalize_lines",
    "parse_wurst_file",
    "write_recipes_to_file",
]

